<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-Y74MT1V5JC"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-Y74MT1V5JC');
    </script>
    <link rel="icon" type="image/png" href="/Logo Xzenpress oficial.png" />
    <link rel="apple-touch-icon" href="/Logo Xzenpress oficial.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#059669" />
    <meta name="description" content="XZenPress - Plataforma de bem-estar holística com acupressão MTC, respiração 4-7-8 e cromoterapia" />
    <link rel="manifest" href="/manifest.json" />
    <title>XZenPress</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>