import React, { createContext, useContext, useState } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const languages: Language[] = [
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
];

const translations: Record<string, Record<string, string>> = {
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.acupressure': 'Acupressão',
    'nav.breathing': 'Respiração',
    'nav.premium': 'Premium',
    'nav.login': 'Entrar',
    'nav.logout': 'Sair',
    
    // Home Page
    'home.hero.title': 'Transforme sua vida com terapias Wellness',
    'home.hero.subtitle': 'Acupressão, respiração 4-7-8, cromoterapia e sons harmonizantes em uma plataforma única',
    'home.hero.startNow': 'Começar Agora',
    'home.hero.createAccount': 'Criar Conta Gratuita',
    'home.features.title': 'Terapias Integradas para seu Bem-Estar',
    'home.features.subtitle': 'Combine o melhor da medicina tradicional com tecnologia moderna',
    'home.feature.acupressure.title': 'Acupressão Ocupacional',
    'home.feature.acupressure.desc': 'Técnicas de MTC adaptadas para alívio do estresse no ambiente de trabalho, reduzindo tensões musculares e ansiedade ocupacional',
    'home.feature.cranio.title': 'Cranioterapia Corporativa',
    'home.feature.cranio.desc': 'Protocolos específicos para alívio de cefaleia tensional, fadiga mental e sobrecarga cognitiva relacionadas ao trabalho',
    'home.feature.breathing.title': 'Respiração Anti-Estresse',
    'home.feature.breathing.desc': 'Técnica 4-7-8 cientificamente validada para redução imediata da ansiedade e regulação do sistema nervoso durante o expediente',
    'home.feature.chromotherapy.title': 'Cromoterapia Ambiental',
    'home.feature.chromotherapy.desc': 'Aplicação de cores terapêuticas para otimização do ambiente de trabalho e redução de riscos psicossociais',
    'home.feature.sounds.title': 'Soundscaping Corporativo',
    'home.feature.sounds.desc': 'Paisagens sonoras especializadas para mascaramento de ruído ocupacional e promoção de foco e concentração',
    'home.feature.consultation.title': 'Consultoria Especializada',
    'home.cta.title': 'Sua empresa promove a saúde integral, Wellness no ambiente de trabalho full time?',
    'home.cta.subtitle': 'Implemente agora práticas de saúde mental e almeje a certificação de Empresa Promotora da Saúde.',
    'home.cta.demo': 'Demonstração Gratuita',
    'home.cta.corporate': 'Consultoria Corporativa',
    'home.compliance.title': 'Conformidade Legal e Científica',
    'home.compliance.subtitle': 'Nossa plataforma foi desenvolvida em total conformidade com a legislação brasileira e baseada em evidências científicas reconhecidas internacionalmente',
    'home.compliance.law.title': 'Lei 14.831/2024',
    'home.compliance.nr1.title': 'NR-1 Compliance',
    'home.wellness.title': 'Busca do Wellness Corporativo',
    'home.wellness.desc': 'Nossa metodologia auxilia sua empresa se tornar uma Empresa Promotora da Saúde Mental, auxiliando no atendimento integral aos requisitos da Lei 14.831/2024 e NR-1, com efetividade online durante todo o processo.',
    
    // Login Page
    'login.welcome': 'Bem-vindo de volta!',
    'login.createAccount': 'Criar Conta',
    'login.subtitle.login': 'Entre na sua conta XZenPress',
    'login.subtitle.register': 'Junte-se à nossa comunidade de bem-estar',
    'login.name': 'Nome Completo',
    'login.email': 'Email',
    'login.password': 'Senha',
    'login.confirmPassword': 'Confirmar Senha',
    'login.forgotPassword': 'Esqueceu a senha?',
    'login.noAccount': 'Não tem conta? Criar uma',
    'login.hasAccount': 'Já tem conta? Fazer login',
    'login.demo.title': 'Para testar:',
    'login.demo.desc': 'Use qualquer email válido e senha com 6+ caracteres',
    'login.reset.title': 'Recuperar Senha',
    'login.reset.subtitle': 'Digite seu email para receber o link de recuperação',
    'login.reset.send': 'Enviar Link de Recuperação',
    'login.reset.back': 'Voltar ao Login',
    
    // Breathing Exercise
    'breathing.title': 'Técnica de Respiração 4-7-8',
    'breathing.inhale': 'Inspire',
    'breathing.hold': 'Segure',
    'breathing.exhale': 'Expire',
    'breathing.start': 'Iniciar Sessão',
    'breathing.stop': 'Parar',
    'breathing.reset': 'Reset',
    'breathing.totalTime': 'Tempo Total',
    'breathing.chromotherapy.title': 'Cromoterapia Integrada',
    'breathing.chromotherapy.description': 'Cada cor possui propriedades terapêuticas específicas que potencializam os benefícios da respiração 4-7-8',
    'breathing.chromotherapy.blue': 'Azul - Calma e Tranquilidade',
    'breathing.chromotherapy.blue.desc': 'Durante a inspiração, o azul promove relaxamento profundo e reduz a ansiedade.',
    'breathing.chromotherapy.green': 'Verde - Equilíbrio e Harmonia',
    'breathing.chromotherapy.green.desc': 'Na retenção, o verde equilibra o sistema nervoso e promove estabilidade emocional.',
    'breathing.chromotherapy.magenta': 'Magenta - Renovação e Energia',
    'breathing.chromotherapy.magenta.desc': 'Na expiração, o magenta facilita a liberação de tensões e renova a energia vital.',
    'breathing.chromotherapy.blue.short': 'Azul da Calma',
    'breathing.chromotherapy.green.short': 'Verde do Equilíbrio',
    'breathing.chromotherapy.magenta.short': 'Magenta da Renovação',
    'breathing.benefits.title': 'Benefícios da Técnica 4-7-8',
    'breathing.benefits.stress': 'Reduz estresse e ansiedade',
    'breathing.benefits.sleep': 'Melhora qualidade do sono',
    'breathing.benefits.focus': 'Aumenta foco e concentração',
    'breathing.benefits.pressure': 'Regula pressão arterial',
    'breathing.sounds.title': 'Sons Harmonizantes',
    'breathing.sounds.free.title': 'Sons Gratuitos',
    'breathing.sounds.premium.title': 'Sons Premium',
    'breathing.sounds.ocean': 'Sons do Mar',
    'breathing.sounds.ocean.desc': 'Ondas relaxantes do oceano',
    'breathing.sounds.rain': 'Chuva Suave',
    'breathing.sounds.rain.desc': 'Som calmante de chuva',
    'breathing.sounds.forest': 'Floresta',
    'breathing.sounds.fireplace': 'Lareira',
    'breathing.sounds.classical': 'Música Clássica',
    'breathing.sounds.mantras': 'Mantras',
    'breathing.sounds.more': '+ 46 mais',
    'breathing.sounds.play': 'Reproduzir',
    'breathing.sounds.pause': 'Pausar',
    'breathing.sounds.stop': 'Parar Tudo',
    'breathing.sounds.premium.desc': 'Desbloqueie nossa biblioteca completa com mais de 50 sons relaxantes e integração com Spotify Premium',
    'breathing.sounds.premium.upgrade': 'Fazer Upgrade',
    'breathing.sounds.premium.spotify': 'Spotify Premium',
    'breathing.science.title': 'Base Científica da Técnica 4-7-8',
    'breathing.science.evidence': 'Evidências Científicas',
    'breathing.science.chromotherapy': 'Cromoterapia Científica',
    'breathing.science.parasympathetic': 'Ativa o sistema nervoso parassimpático',
    'breathing.science.cortisol': 'Reduz cortisol (hormônio do estresse)',
    'breathing.science.heartRate': 'Melhora variabilidade da frequência cardíaca',
    'breathing.science.gaba': 'Aumenta produção de GABA (neurotransmissor calmante)',
    'breathing.science.blue.effect': 'Azul: Reduz pressão arterial e frequência cardíaca',
    'breathing.science.green.effect': 'Verde: Equilibra sistema nervoso autônomo',
    'breathing.science.magenta.effect': 'Magenta: Estimula liberação de endorfinas',
    'breathing.science.melatonin': 'Cores influenciam produção de melatonina',
    'breathing.phase': 'Fase',
    'breathing.phase.inhale.detail': 'Inspiração (4 segundos)',
    'breathing.phase.hold.detail': 'Retenção (7 segundos)',
    'breathing.phase.exhale.detail': 'Expiração (8 segundos)',
    
    // Acupressure Page
    'acupressure.title': 'Acupressão & Cranioterapia',
    'acupressure.subtitle': 'Pontos terapêuticos da Medicina Tradicional Chinesa combinados com cromoterapia',
    'acupressure.categories.title': 'Categorias de Pontos',
    'acupressure.category.all': 'Todos os Pontos',
    'acupressure.category.general': 'MTC (Medicina Tradicional Chinesa)',
    'acupressure.category.cranio': 'Craniopuntura',
    'acupressure.category.septicemia': 'Septicemia',
    'acupressure.category.atm': 'ATM',
    'acupressure.chromotherapy.title': 'Cromoterapia',
    'acupressure.chromotherapy.desc': 'A cromoterapia é automaticamente integrada ao timer dos pontos quando ativada',
    'acupressure.chromotherapy.manual': 'Cromoterapia Manual (1min)',
    'acupressure.chromotherapy.active': 'Cromoterapia Ativa...',
    'acupressure.chromotherapy.note': 'Use este botão apenas para cromoterapia independente',
    'acupressure.points.visual.title': 'Pontos Terapêuticos Visuais',
    'acupressure.points.select': 'Selecione um Ponto',
    'acupressure.points.select.desc': 'Clique em qualquer ponto no diagrama para ver detalhes e benefícios',
    'acupressure.points.free': 'Pontos Gratuitos',
    'acupressure.points.premium': 'Pontos Premium',
    'acupressure.therapy.integrated': 'Terapia Integrada',
    'acupressure.therapy.breathing': 'Respiração Integrada 4-7-8',
    'acupressure.therapy.start': 'Iniciar Acupressão + Respiração 4-7-8',
    'acupressure.therapy.stop': 'Parar Terapia Integrada',
    'acupressure.guide.title': 'Guia de Aplicação Integrada',
    'acupressure.guide.breathing': 'Respiração + Acupressão:',
    'acupressure.guide.results': 'Maximização dos Resultados:',
    'acupressure.science.title': 'Ciência por trás da Integração',
    'acupressure.science.desc': 'A combinação de acupressão + respiração 4-7-8 + cromoterapia ativa simultaneamente: o sistema nervoso parassimpático, pontos de acupuntura tradicionais e receptores visuais, criando um efeito sinérgico para máximo relaxamento e bem-estar.',
    'acupressure.premium.unlock': 'Desbloqueie Pontos Específicos',
    'acupressure.premium.desc': 'Acesse pontos especializados para septicemia, ATM, cranioterapia e muito mais',
    'acupressure.premium.upgrade': 'Fazer Upgrade Premium',
    'acupressure.stats.title': 'Estatísticas da Plataforma',
    'acupressure.stats.available': 'Pontos Disponíveis',
    'acupressure.stats.free': 'Pontos Gratuitos',
    'acupressure.stats.premium': 'Pontos Premium',
    'acupressure.stats.categories': 'Categorias',
    'acupressure.tips.title': 'Dicas de Bem-Estar',
    'acupressure.tips.morning': 'Rotina Matinal',
    'acupressure.tips.sleep': 'Antes de Dormir',
    'acupressure.tips.work': 'No Trabalho',
    'acupressure.tips.focus': 'Foco e Concentração',
    'acupressure.safety.title': 'Aviso Importante',
    'acupressure.safety.desc': 'A acupressão é uma técnica complementar e não substitui tratamento médico. Em caso de condições graves como septicemia, procure sempre assistência médica profissional. Os pontos premium são baseados em técnicas tradicionais e devem ser usados como apoio ao tratamento convencional.',
    
    // Premium Page
    'premium.title': 'Desbloqueie Todo o Potencial',
    'premium.subtitle': 'Acesso completo a consultas especializadas e recursos terapêuticos avançados',
    'premium.user.active': 'Usuário Premium Ativo',
    'premium.upgrade': 'Upgrade para Premium',
    'premium.features.title': 'Recursos Premium Disponíveis',
    'premium.whatsapp.title': 'Consulta WhatsApp Especializada',
    'premium.whatsapp.desc': 'Atendimento direto com Alexandre Pinheiro - 15 anos de experiência',
    'premium.points.title': 'Pontos de Acupressão Específicos',
    'premium.points.desc': 'Acesso a pontos especializados para condições específicas',
    'premium.chromotherapy.title': 'Cromoterapia Avançada',
    'premium.chromotherapy.desc': 'Sequências de cores personalizadas para diferentes condições',
    'premium.sounds.title': 'Biblioteca Completa de Sons',
    'premium.sounds.desc': 'Mais de 50 sons terapêuticos + integração Spotify',
    'premium.ai.title': 'Recomendações Personalizadas IA',
    'premium.ai.desc': 'Sistema inteligente que aprende com seus padrões',
    'premium.offline.title': 'Modo Offline Completo',
    'premium.offline.desc': 'Acesso total sem conexão com internet',
    'premium.pricing.title': 'Escolha Seu Plano Premium',
    'premium.pricing.subtitle': 'Invista no seu bem-estar com acesso completo a todas as funcionalidades terapêuticas',
    'premium.plan.monthly': 'Premium Mensal',
    'premium.plan.annual': 'Premium Anual',
    'premium.plan.lifetime': 'Premium Vitalício',
    'premium.testimonials.title': 'O que dizem nossos usuários Premium',
    'premium.faq.title': 'Perguntas Frequentes',
    'premium.available': 'Disponível',
    'premium.coming.soon': 'Em Breve',
    'premium.popular': 'Mais Popular',
    'premium.choose.plan': 'Escolher Plano',
    
    // WhatsApp Consultation
    'whatsapp.title': 'Consulta Especializada',
    'whatsapp.subtitle': 'Para casos complexos que precisam de atenção personalizada',
    'whatsapp.form.title': 'Formulário de Consulta',
    'whatsapp.form.subtitle': 'Preencha os dados abaixo para receber atendimento personalizado via WhatsApp',
    'whatsapp.form.name': 'Nome Completo',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.urgency': 'Nível de Urgência',
    'whatsapp.form.condition': 'Condição Principal',
    'whatsapp.form.duration': 'Há quanto tempo tem esses sintomas?',
    'whatsapp.form.symptoms': 'Descreva seus sintomas detalhadamente',
    'whatsapp.form.treatments': 'Tratamentos já realizados',
    'whatsapp.form.medications': 'Medicamentos atuais',
    'whatsapp.form.schedule': 'Preferência de horário para retorno',
    'whatsapp.form.send': 'Enviar via WhatsApp',
    'whatsapp.form.note': 'Ao enviar, você será redirecionado para o WhatsApp com sua mensagem pré-formatada',
    'whatsapp.important.title': 'Importante:',
    'whatsapp.important.desc': 'Este serviço não substitui consulta médica. Em casos de emergência, procure atendimento médico imediatamente.',
    'whatsapp.back': 'Voltar',
    
    // Points data
    'points.yintang.name': 'Yintang (EX-HN3)',
    'points.yintang.desc': 'Localizado entre as sobrancelhas, no centro da testa. Ponto principal para reduzir estresse, ansiedade e tensão diária.',
    'points.baihui.name': 'Baihui (VG20)',
    'points.baihui.desc': 'Ponto de encontro de vários meridianos yang. Abordagem energética MTC para elevar a mente, recuperar a consciência e combater fadiga mental.',
    'points.cranio.frontal.name': 'Ponto Frontal Craniano',
    'points.cranio.frontal.desc': 'Localizado na região frontal, técnica craniana específica para reduzir estresse e ansiedade através da estimulação direta do córtex frontal.',
    'points.cranio.cerebro.name': 'Pontos Cérebro e Cerebelo',
    'points.cranio.cerebro.desc': 'Pontos específicos do cérebro e cerebelo para sono, tonturas, dores crônicas, fadiga mental e clareza. Técnica craniana avançada para otimização das funções cerebrais.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.acupressure': 'Acupressure',
    'nav.breathing': 'Breathing',
    'nav.premium': 'Premium',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Home Page
    'home.hero.title': 'Transform your life with Wellness therapies',
    'home.hero.subtitle': 'Acupressure, 4-7-8 breathing, chromotherapy and harmonizing sounds in a unique platform',
    'home.hero.startNow': 'Start Now',
    'home.hero.createAccount': 'Create Free Account',
    'home.features.title': 'Integrated Therapies for your Well-Being',
    'home.features.subtitle': 'Combine the best of traditional medicine with modern technology',
    'home.feature.acupressure.title': 'Occupational Acupressure',
    'home.feature.acupressure.desc': 'TCM techniques adapted for workplace stress relief, reducing muscle tension and occupational anxiety',
    'home.feature.cranio.title': 'Corporate Craniotherapy',
    'home.feature.cranio.desc': 'Specific protocols for tension headache relief, mental fatigue and work-related cognitive overload',
    'home.feature.breathing.title': 'Anti-Stress Breathing',
    'home.feature.breathing.desc': 'Scientifically validated 4-7-8 technique for immediate anxiety reduction and nervous system regulation during work hours',
    'home.feature.chromotherapy.title': 'Environmental Chromotherapy',
    'home.feature.chromotherapy.desc': 'Application of therapeutic colors for workplace optimization and psychosocial risk reduction',
    'home.feature.sounds.title': 'Corporate Soundscaping',
    'home.feature.sounds.desc': 'Specialized soundscapes for occupational noise masking and focus and concentration promotion',
    'home.feature.consultation.title': 'Specialized Consultation',
    'home.cta.title': 'Does your company promote integral health, full-time Wellness in the workplace?',
    'home.cta.subtitle': 'Implement mental health practices now and aim for Health Promoting Company certification.',
    'home.cta.demo': 'Free Demo',
    'home.cta.corporate': 'Corporate Consultation',
    'home.compliance.title': 'Legal and Scientific Compliance',
    'home.compliance.subtitle': 'Our platform was developed in full compliance with Brazilian legislation and based on internationally recognized scientific evidence',
    'home.compliance.law.title': 'Law 14.831/2024',
    'home.compliance.nr1.title': 'NR-1 Compliance',
    'home.wellness.title': 'Corporate Wellness Quest',
    'home.wellness.desc': 'Our methodology helps your company become a Mental Health Promoting Company, assisting in full compliance with Law 14.831/2024 and NR-1 requirements, with online effectiveness throughout the process.',
    
    // Login Page
    'login.welcome': 'Welcome back!',
    'login.createAccount': 'Create Account',
    'login.subtitle.login': 'Sign in to your XZenPress account',
    'login.subtitle.register': 'Join our wellness community',
    'login.name': 'Full Name',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.confirmPassword': 'Confirm Password',
    'login.forgotPassword': 'Forgot password?',
    'login.noAccount': 'No account? Create one',
    'login.hasAccount': 'Already have an account? Sign in',
    'login.demo.title': 'To test:',
    'login.demo.desc': 'Use any valid email and password with 6+ characters',
    'login.reset.title': 'Reset Password',
    'login.reset.subtitle': 'Enter your email to receive the recovery link',
    'login.reset.send': 'Send Recovery Link',
    'login.reset.back': 'Back to Login',
    
    // Breathing Exercise
    'breathing.title': '4-7-8 Breathing Technique',
    'breathing.inhale': 'Inhale',
    'breathing.hold': 'Hold',
    'breathing.exhale': 'Exhale',
    'breathing.start': 'Start Session',
    'breathing.stop': 'Stop',
    'breathing.reset': 'Reset',
    'breathing.totalTime': 'Total Time',
    'breathing.chromotherapy.title': 'Integrated Chromotherapy',
    'breathing.chromotherapy.description': 'Each color has specific therapeutic properties that enhance the benefits of 4-7-8 breathing',
    'breathing.chromotherapy.blue': 'Blue - Calm and Tranquility',
    'breathing.chromotherapy.blue.desc': 'During inhalation, blue promotes deep relaxation and reduces anxiety.',
    'breathing.chromotherapy.green': 'Green - Balance and Harmony',
    'breathing.chromotherapy.green.desc': 'During retention, green balances the nervous system and promotes emotional stability.',
    'breathing.chromotherapy.magenta': 'Magenta - Renewal and Energy',
    'breathing.chromotherapy.magenta.desc': 'During exhalation, magenta facilitates tension release and renews vital energy.',
    'breathing.chromotherapy.blue.short': 'Blue of Calm',
    'breathing.chromotherapy.green.short': 'Green of Balance',
    'breathing.chromotherapy.magenta.short': 'Magenta of Renewal',
    'breathing.benefits.title': 'Benefits of 4-7-8 Technique',
    'breathing.benefits.stress': 'Reduces stress and anxiety',
    'breathing.benefits.sleep': 'Improves sleep quality',
    'breathing.benefits.focus': 'Increases focus and concentration',
    'breathing.benefits.pressure': 'Regulates blood pressure',
    'breathing.sounds.title': 'Harmonizing Sounds',
    'breathing.sounds.free.title': 'Free Sounds',
    'breathing.sounds.premium.title': 'Premium Sounds',
    'breathing.sounds.ocean': 'Ocean Sounds',
    'breathing.sounds.ocean.desc': 'Relaxing ocean waves',
    'breathing.sounds.rain': 'Gentle Rain',
    'breathing.sounds.rain.desc': 'Calming rain sound',
    'breathing.sounds.forest': 'Forest',
    'breathing.sounds.fireplace': 'Fireplace',
    'breathing.sounds.classical': 'Classical Music',
    'breathing.sounds.mantras': 'Mantras',
    'breathing.sounds.more': '+ 46 more',
    'breathing.sounds.play': 'Play',
    'breathing.sounds.pause': 'Pause',
    'breathing.sounds.stop': 'Stop All',
    'breathing.sounds.premium.desc': 'Unlock our complete library with over 50 relaxing sounds and Spotify Premium integration',
    'breathing.sounds.premium.upgrade': 'Upgrade Now',
    'breathing.sounds.premium.spotify': 'Spotify Premium',
    'breathing.science.title': 'Scientific Basis of 4-7-8 Technique',
    'breathing.science.evidence': 'Scientific Evidence',
    'breathing.science.chromotherapy': 'Scientific Chromotherapy',
    'breathing.science.parasympathetic': 'Activates parasympathetic nervous system',
    'breathing.science.cortisol': 'Reduces cortisol (stress hormone)',
    'breathing.science.heartRate': 'Improves heart rate variability',
    'breathing.science.gaba': 'Increases GABA production (calming neurotransmitter)',
    'breathing.science.blue.effect': 'Blue: Reduces blood pressure and heart rate',
    'breathing.science.green.effect': 'Green: Balances autonomic nervous system',
    'breathing.science.magenta.effect': 'Magenta: Stimulates endorphin release',
    'breathing.science.melatonin': 'Colors influence melatonin production',
    'breathing.phase': 'Phase',
    'breathing.phase.inhale.detail': 'Inhalation (4 seconds)',
    'breathing.phase.hold.detail': 'Retention (7 seconds)',
    'breathing.phase.exhale.detail': 'Exhalation (8 seconds)',
    
    // Acupressure Page
    'acupressure.title': 'Acupressure & Craniotherapy',
    'acupressure.subtitle': 'Traditional Chinese Medicine therapeutic points combined with chromotherapy',
    'acupressure.categories.title': 'Point Categories',
    'acupressure.category.all': 'All Points',
    'acupressure.category.general': 'TCM (Traditional Chinese Medicine)',
    'acupressure.category.cranio': 'Craniopuncture',
    'acupressure.category.septicemia': 'Septicemia',
    'acupressure.category.atm': 'TMJ',
    'acupressure.chromotherapy.title': 'Chromotherapy',
    'acupressure.chromotherapy.desc': 'Chromotherapy is automatically integrated into the point timer when activated',
    'acupressure.chromotherapy.manual': 'Manual Chromotherapy (1min)',
    'acupressure.chromotherapy.active': 'Chromotherapy Active...',
    'acupressure.chromotherapy.note': 'Use this button only for independent chromotherapy',
    'acupressure.points.visual.title': 'Visual Therapeutic Points',
    'acupressure.points.select': 'Select a Point',
    'acupressure.points.select.desc': 'Click on any point in the diagram to see details and benefits',
    'acupressure.points.free': 'Free Points',
    'acupressure.points.premium': 'Premium Points',
    'acupressure.therapy.integrated': 'Integrated Therapy',
    'acupressure.therapy.breathing': 'Integrated 4-7-8 Breathing',
    'acupressure.therapy.start': 'Start Acupressure + 4-7-8 Breathing',
    'acupressure.therapy.stop': 'Stop Integrated Therapy',
    'acupressure.guide.title': 'Integrated Application Guide',
    'acupressure.guide.breathing': 'Breathing + Acupressure:',
    'acupressure.guide.results': 'Maximizing Results:',
    'acupressure.science.title': 'Science behind Integration',
    'acupressure.science.desc': 'The combination of acupressure + 4-7-8 breathing + chromotherapy simultaneously activates: the parasympathetic nervous system, traditional acupuncture points and visual receptors, creating a synergistic effect for maximum relaxation and well-being.',
    'acupressure.premium.unlock': 'Unlock Specific Points',
    'acupressure.premium.desc': 'Access specialized points for septicemia, TMJ, craniotherapy and much more',
    'acupressure.premium.upgrade': 'Premium Upgrade',
    'acupressure.stats.title': 'Platform Statistics',
    'acupressure.stats.available': 'Available Points',
    'acupressure.stats.free': 'Free Points',
    'acupressure.stats.premium': 'Premium Points',
    'acupressure.stats.categories': 'Categories',
    'acupressure.tips.title': 'Wellness Tips',
    'acupressure.tips.morning': 'Morning Routine',
    'acupressure.tips.sleep': 'Before Sleep',
    'acupressure.tips.work': 'At Work',
    'acupressure.tips.focus': 'Focus and Concentration',
    'acupressure.safety.title': 'Important Notice',
    'acupressure.safety.desc': 'Acupressure is a complementary technique and does not replace medical treatment. In case of serious conditions like septicemia, always seek professional medical assistance. Premium points are based on traditional techniques and should be used as support to conventional treatment.',
    
    // Premium Page
    'premium.title': 'Unlock Full Potential',
    'premium.subtitle': 'Complete access to specialized consultations and advanced therapeutic resources',
    'premium.user.active': 'Active Premium User',
    'premium.upgrade': 'Upgrade to Premium',
    'premium.features.title': 'Available Premium Features',
    'premium.whatsapp.title': 'Specialized WhatsApp Consultation',
    'premium.whatsapp.desc': 'Direct service with Alexandre Pinheiro - 15 years of experience',
    'premium.points.title': 'Specific Acupressure Points',
    'premium.points.desc': 'Access to specialized points for specific conditions',
    'premium.chromotherapy.title': 'Advanced Chromotherapy',
    'premium.chromotherapy.desc': 'Personalized color sequences for different conditions',
    'premium.sounds.title': 'Complete Sound Library',
    'premium.sounds.desc': 'Over 50 therapeutic sounds + Spotify integration',
    'premium.ai.title': 'Personalized AI Recommendations',
    'premium.ai.desc': 'Intelligent system that learns from your patterns',
    'premium.offline.title': 'Complete Offline Mode',
    'premium.offline.desc': 'Full access without internet connection',
    'premium.pricing.title': 'Choose Your Premium Plan',
    'premium.pricing.subtitle': 'Invest in your well-being with complete access to all therapeutic functionalities',
    'premium.plan.monthly': 'Monthly Premium',
    'premium.plan.annual': 'Annual Premium',
    'premium.plan.lifetime': 'Lifetime Premium',
    'premium.testimonials.title': 'What our Premium users say',
    'premium.faq.title': 'Frequently Asked Questions',
    'premium.available': 'Available',
    'premium.coming.soon': 'Coming Soon',
    'premium.popular': 'Most Popular',
    'premium.choose.plan': 'Choose Plan',
    
    // WhatsApp Consultation
    'whatsapp.title': 'Specialized Consultation',
    'whatsapp.subtitle': 'For complex cases that need personalized attention',
    'whatsapp.form.title': 'Consultation Form',
    'whatsapp.form.subtitle': 'Fill in the data below to receive personalized service via WhatsApp',
    'whatsapp.form.name': 'Full Name',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.urgency': 'Urgency Level',
    'whatsapp.form.condition': 'Main Condition',
    'whatsapp.form.duration': 'How long have you had these symptoms?',
    'whatsapp.form.symptoms': 'Describe your symptoms in detail',
    'whatsapp.form.treatments': 'Treatments already performed',
    'whatsapp.form.medications': 'Current medications',
    'whatsapp.form.schedule': 'Time preference for return',
    'whatsapp.form.send': 'Send via WhatsApp',
    'whatsapp.form.note': 'When sending, you will be redirected to WhatsApp with your pre-formatted message',
    'whatsapp.important.title': 'Important:',
    'whatsapp.important.desc': 'This service does not replace medical consultation. In case of emergency, seek medical attention immediately.',
    'whatsapp.back': 'Back',
    
    // Points data
    'points.yintang.name': 'Yintang (EX-HN3)',
    'points.yintang.desc': 'Located between the eyebrows, center of forehead. Main point for reducing stress, anxiety and daily tension.',
    'points.baihui.name': 'Baihui (VG20)',
    'points.baihui.desc': 'Meeting point of several yang meridians. TCM energetic approach to elevate the mind, recover consciousness and combat mental fatigue.',
    'points.cranio.frontal.name': 'Cranial Frontal Point',
    'points.cranio.frontal.desc': 'Located in frontal region, specific cranial technique to reduce stress and anxiety through direct frontal cortex stimulation.',
    'points.cranio.cerebro.name': 'Brain and Cerebellum Points',
    'points.cranio.cerebro.desc': 'Specific brain and cerebellum points for sleep, dizziness, chronic pain, mental fatigue and clarity. Advanced cranial technique for brain function optimization.',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.acupressure': 'Acupresión',
    'nav.breathing': 'Respiración',
    'nav.premium': 'Premium',
    'nav.login': 'Iniciar Sesión',
    'nav.logout': 'Cerrar Sesión',
    
    // Home Page
    'home.hero.title': 'Transforma tu vida con terapias Wellness',
    'home.hero.subtitle': 'Acupresión, respiración 4-7-8, cromoterapia y sonidos armonizantes en una plataforma única',
    'home.hero.startNow': 'Comenzar Ahora',
    'home.hero.createAccount': 'Crear Cuenta Gratuita',
    'home.features.title': 'Terapias Integradas para tu Bienestar',
    'home.features.subtitle': 'Combina lo mejor de la medicina tradicional con tecnología moderna',
    'home.feature.acupressure.title': 'Acupresión Ocupacional',
    'home.feature.acupressure.desc': 'Técnicas de MTC adaptadas para alivio del estrés en el ambiente laboral, reduciendo tensiones musculares y ansiedad ocupacional',
    'home.feature.cranio.title': 'Craneoterapia Corporativa',
    'home.feature.cranio.desc': 'Protocolos específicos para alivio de cefalea tensional, fatiga mental y sobrecarga cognitiva relacionadas al trabajo',
    'home.feature.breathing.title': 'Respiración Anti-Estrés',
    'home.feature.breathing.desc': 'Técnica 4-7-8 científicamente validada para reducción inmediata de ansiedad y regulación del sistema nervioso durante el horario laboral',
    'home.feature.chromotherapy.title': 'Cromoterapia Ambiental',
    'home.feature.chromotherapy.desc': 'Aplicación de colores terapéuticos para optimización del ambiente laboral y reducción de riesgos psicosociales',
    'home.feature.sounds.title': 'Soundscaping Corporativo',
    'home.feature.sounds.desc': 'Paisajes sonoros especializados para enmascaramiento de ruido ocupacional y promoción de enfoque y concentración',
    'home.feature.consultation.title': 'Consultoría Especializada',
    'home.cta.title': '¿Tu empresa promueve la salud integral, Wellness en el ambiente laboral tiempo completo?',
    'home.cta.subtitle': 'Implementa ahora prácticas de salud mental y aspira a la certificación de Empresa Promotora de la Salud.',
    'home.cta.demo': 'Demostración Gratuita',
    'home.cta.corporate': 'Consultoría Corporativa',
    'home.compliance.title': 'Conformidad Legal y Científica',
    'home.compliance.subtitle': 'Nuestra plataforma fue desarrollada en total conformidad con la legislación brasileña y basada en evidencias científicas reconocidas internacionalmente',
    'home.compliance.law.title': 'Ley 14.831/2024',
    'home.compliance.nr1.title': 'Conformidad NR-1',
    'home.wellness.title': 'Búsqueda del Wellness Corporativo',
    'home.wellness.desc': 'Nuestra metodología ayuda a tu empresa a convertirse en una Empresa Promotora de la Salud Mental, asistiendo en el cumplimiento integral de los requisitos de la Ley 14.831/2024 y NR-1, con efectividad online durante todo el proceso.',
    
    // Login Page
    'login.welcome': '¡Bienvenido de vuelta!',
    'login.createAccount': 'Crear Cuenta',
    'login.subtitle.login': 'Inicia sesión en tu cuenta XZenPress',
    'login.subtitle.register': 'Únete a nuestra comunidad de bienestar',
    'login.name': 'Nombre Completo',
    'login.email': 'Email',
    'login.password': 'Contraseña',
    'login.confirmPassword': 'Confirmar Contraseña',
    'login.forgotPassword': '¿Olvidaste la contraseña?',
    'login.noAccount': '¿No tienes cuenta? Crear una',
    'login.hasAccount': '¿Ya tienes cuenta? Iniciar sesión',
    'login.demo.title': 'Para probar:',
    'login.demo.desc': 'Usa cualquier email válido y contraseña con 6+ caracteres',
    'login.reset.title': 'Recuperar Contraseña',
    'login.reset.subtitle': 'Ingresa tu email para recibir el enlace de recuperación',
    'login.reset.send': 'Enviar Enlace de Recuperación',
    'login.reset.back': 'Volver al Login',
    
    // Breathing Exercise
    'breathing.title': 'Técnica de Respiración 4-7-8',
    'breathing.inhale': 'Inhalar',
    'breathing.hold': 'Mantener',
    'breathing.exhale': 'Exhalar',
    'breathing.start': 'Iniciar Sesión',
    'breathing.stop': 'Parar',
    'breathing.reset': 'Reset',
    'breathing.totalTime': 'Tiempo Total',
    'breathing.chromotherapy.title': 'Cromoterapia Integrada',
    'breathing.chromotherapy.description': 'Cada color tiene propiedades terapéuticas específicas que potencian los beneficios de la respiración 4-7-8',
    'breathing.chromotherapy.blue': 'Azul - Calma y Tranquilidad',
    'breathing.chromotherapy.blue.desc': 'Durante la inhalación, el azul promueve relajación profunda y reduce la ansiedad.',
    'breathing.chromotherapy.green': 'Verde - Equilibrio y Armonía',
    'breathing.chromotherapy.green.desc': 'Durante la retención, el verde equilibra el sistema nervioso y promueve estabilidad emocional.',
    'breathing.chromotherapy.magenta': 'Magenta - Renovación y Energía',
    'breathing.chromotherapy.magenta.desc': 'Durante la exhalación, el magenta facilita la liberación de tensiones y renueva la energía vital.',
    'breathing.chromotherapy.blue.short': 'Azul de la Calma',
    'breathing.chromotherapy.green.short': 'Verde del Equilibrio',
    'breathing.chromotherapy.magenta.short': 'Magenta de la Renovación',
    'breathing.benefits.title': 'Beneficios de la Técnica 4-7-8',
    'breathing.benefits.stress': 'Reduce estrés y ansiedad',
    'breathing.benefits.sleep': 'Mejora calidad del sueño',
    'breathing.benefits.focus': 'Aumenta enfoque y concentración',
    'breathing.benefits.pressure': 'Regula presión arterial',
    'breathing.sounds.title': 'Sonidos Armonizantes',
    'breathing.sounds.free.title': 'Sonidos Gratuitos',
    'breathing.sounds.premium.title': 'Sonidos Premium',
    'breathing.sounds.ocean': 'Sonidos del Mar',
    'breathing.sounds.ocean.desc': 'Olas relajantes del océano',
    'breathing.sounds.rain': 'Lluvia Suave',
    'breathing.sounds.rain.desc': 'Sonido calmante de lluvia',
    'breathing.sounds.forest': 'Bosque',
    'breathing.sounds.fireplace': 'Chimenea',
    'breathing.sounds.classical': 'Música Clásica',
    'breathing.sounds.mantras': 'Mantras',
    'breathing.sounds.more': '+ 46 más',
    'breathing.sounds.play': 'Reproducir',
    'breathing.sounds.pause': 'Pausar',
    'breathing.sounds.stop': 'Parar Todo',
    'breathing.sounds.premium.desc': 'Desbloquea nuestra biblioteca completa con más de 50 sonidos relajantes e integración con Spotify Premium',
    'breathing.sounds.premium.upgrade': 'Actualizar Ahora',
    'breathing.sounds.premium.spotify': 'Spotify Premium',
    'breathing.science.title': 'Base Científica de la Técnica 4-7-8',
    'breathing.science.evidence': 'Evidencia Científica',
    'breathing.science.chromotherapy': 'Cromoterapia Científica',
    'breathing.science.parasympathetic': 'Activa el sistema nervioso parasimpático',
    'breathing.science.cortisol': 'Reduce cortisol (hormona del estrés)',
    'breathing.science.heartRate': 'Mejora variabilidad de frecuencia cardíaca',
    'breathing.science.gaba': 'Aumenta producción de GABA (neurotransmisor calmante)',
    'breathing.science.blue.effect': 'Azul: Reduce presión arterial y frecuencia cardíaca',
    'breathing.science.green.effect': 'Verde: Equilibra sistema nervioso autónomo',
    'breathing.science.magenta.effect': 'Magenta: Estimula liberación de endorfinas',
    'breathing.science.melatonin': 'Los colores influyen en la producción de melatonina',
    'breathing.phase': 'Fase',
    'breathing.phase.inhale.detail': 'Inhalación (4 segundos)',
    'breathing.phase.hold.detail': 'Retención (7 segundos)',
    'breathing.phase.exhale.detail': 'Exhalación (8 segundos)',
    
    // Acupressure Page
    'acupressure.title': 'Acupresión y Craneoterapia',
    'acupressure.subtitle': 'Puntos terapéuticos de la Medicina Tradicional China combinados con cromoterapia',
    'acupressure.categories.title': 'Categorías de Puntos',
    'acupressure.category.all': 'Todos los Puntos',
    'acupressure.category.general': 'MTC (Medicina Tradicional China)',
    'acupressure.category.cranio': 'Craniopuntura',
    'acupressure.category.septicemia': 'Septicemia',
    'acupressure.category.atm': 'ATM',
    'acupressure.chromotherapy.title': 'Cromoterapia',
    'acupressure.chromotherapy.desc': 'La cromoterapia se integra automáticamente al temporizador de puntos cuando se activa',
    'acupressure.chromotherapy.manual': 'Cromoterapia Manual (1min)',
    'acupressure.chromotherapy.active': 'Cromoterapia Activa...',
    'acupressure.chromotherapy.note': 'Usa este botón solo para cromoterapia independiente',
    'acupressure.points.visual.title': 'Puntos Terapéuticos Visuales',
    'acupressure.points.select': 'Selecciona un Punto',
    'acupressure.points.select.desc': 'Haz clic en cualquier punto del diagrama para ver detalles y beneficios',
    'acupressure.points.free': 'Puntos Gratuitos',
    'acupressure.points.premium': 'Puntos Premium',
    'acupressure.therapy.integrated': 'Terapia Integrada',
    'acupressure.therapy.breathing': 'Respiración Integrada 4-7-8',
    'acupressure.therapy.start': 'Iniciar Acupresión + Respiración 4-7-8',
    'acupressure.therapy.stop': 'Parar Terapia Integrada',
    'acupressure.guide.title': 'Guía de Aplicación Integrada',
    'acupressure.guide.breathing': 'Respiración + Acupresión:',
    'acupressure.guide.results': 'Maximización de Resultados:',
    'acupressure.science.title': 'Ciencia detrás de la Integración',
    'acupressure.science.desc': 'La combinación de acupresión + respiración 4-7-8 + cromoterapia activa simultáneamente: el sistema nervioso parasimpático, puntos de acupuntura tradicionales y receptores visuales, creando un efecto sinérgico para máxima relajación y bienestar.',
    'acupressure.premium.unlock': 'Desbloquear Puntos Específicos',
    'acupressure.premium.desc': 'Accede a puntos especializados para septicemia, ATM, craneoterapia y mucho más',
    'acupressure.premium.upgrade': 'Actualizar Premium',
    'acupressure.stats.title': 'Estadísticas de la Plataforma',
    'acupressure.stats.available': 'Puntos Disponibles',
    'acupressure.stats.free': 'Puntos Gratuitos',
    'acupressure.stats.premium': 'Puntos Premium',
    'acupressure.stats.categories': 'Categorías',
    'acupressure.tips.title': 'Consejos de Bienestar',
    'acupressure.tips.morning': 'Rutina Matutina',
    'acupressure.tips.sleep': 'Antes de Dormir',
    'acupressure.tips.work': 'En el Trabajo',
    'acupressure.tips.focus': 'Enfoque y Concentración',
    'acupressure.safety.title': 'Aviso Importante',
    'acupressure.safety.desc': 'La acupresión es una técnica complementaria y no reemplaza el tratamiento médico. En caso de condiciones graves como septicemia, busca siempre asistencia médica profesional. Los puntos premium se basan en técnicas tradicionales y deben usarse como apoyo al tratamiento convencional.',
    
    // Premium Page
    'premium.title': 'Desbloquea Todo el Potencial',
    'premium.subtitle': 'Acceso completo a consultas especializadas y recursos terapéuticos avanzados',
    'premium.user.active': 'Usuario Premium Activo',
    'premium.upgrade': 'Actualizar a Premium',
    'premium.features.title': 'Características Premium Disponibles',
    'premium.whatsapp.title': 'Consulta WhatsApp Especializada',
    'premium.whatsapp.desc': 'Atención directa con Alexandre Pinheiro - 15 años de experiencia',
    'premium.points.title': 'Puntos de Acupresión Específicos',
    'premium.points.desc': 'Acceso a puntos especializados para condiciones específicas',
    'premium.chromotherapy.title': 'Cromoterapia Avanzada',
    'premium.chromotherapy.desc': 'Secuencias de colores personalizadas para diferentes condiciones',
    'premium.sounds.title': 'Biblioteca Completa de Sonidos',
    'premium.sounds.desc': 'Más de 50 sonidos terapéuticos + integración Spotify',
    'premium.ai.title': 'Recomendaciones Personalizadas IA',
    'premium.ai.desc': 'Sistema inteligente que aprende de tus patrones',
    'premium.offline.title': 'Modo Offline Completo',
    'premium.offline.desc': 'Acceso total sin conexión a internet',
    'premium.pricing.title': 'Elige tu Plan Premium',
    'premium.pricing.subtitle': 'Invierte en tu bienestar con acceso completo a todas las funcionalidades terapéuticas',
    'premium.plan.monthly': 'Premium Mensual',
    'premium.plan.annual': 'Premium Anual',
    'premium.plan.lifetime': 'Premium Vitalicio',
    'premium.testimonials.title': 'Lo que dicen nuestros usuarios Premium',
    'premium.faq.title': 'Preguntas Frecuentes',
    'premium.available': 'Disponible',
    'premium.coming.soon': 'Próximamente',
    'premium.popular': 'Más Popular',
    'premium.choose.plan': 'Elegir Plan',
    
    // WhatsApp Consultation
    'whatsapp.title': 'Consulta Especializada',
    'whatsapp.subtitle': 'Para casos complejos que necesitan atención personalizada',
    'whatsapp.form.title': 'Formulario de Consulta',
    'whatsapp.form.subtitle': 'Completa los datos a continuación para recibir atención personalizada vía WhatsApp',
    'whatsapp.form.name': 'Nombre Completo',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.urgency': 'Nivel de Urgencia',
    'whatsapp.form.condition': 'Condición Principal',
    'whatsapp.form.duration': '¿Cuánto tiempo tienes estos síntomas?',
    'whatsapp.form.symptoms': 'Describe tus síntomas detalladamente',
    'whatsapp.form.treatments': 'Tratamientos ya realizados',
    'whatsapp.form.medications': 'Medicamentos actuales',
    'whatsapp.form.schedule': 'Preferencia de horario para retorno',
    'whatsapp.form.send': 'Enviar vía WhatsApp',
    'whatsapp.form.note': 'Al enviar, serás redirigido a WhatsApp con tu mensaje pre-formateado',
    'whatsapp.important.title': 'Importante:',
    'whatsapp.important.desc': 'Este servicio no reemplaza la consulta médica. En casos de emergencia, busca atención médica inmediatamente.',
    'whatsapp.back': 'Volver',
    
    // Points data
    'points.yintang.name': 'Yintang (EX-HN3)',
    'points.yintang.desc': 'Ubicado entre las cejas, centro de la frente. Punto principal para reducir estrés, ansiedad y tensión diaria.',
    'points.baihui.name': 'Baihui (VG20)',
    'points.baihui.desc': 'Punto de encuentro de varios meridianos yang. Enfoque energético MTC para elevar la mente, recuperar conciencia y combatir fatiga mental.',
    'points.cranio.frontal.name': 'Punto Frontal Craneal',
    'points.cranio.frontal.desc': 'Ubicado en región frontal, técnica craneal específica para reducir estrés y ansiedad a través de estimulación directa del córtex frontal.',
    'points.cranio.cerebro.name': 'Puntos Cerebro y Cerebelo',
    'points.cranio.cerebro.desc': 'Puntos específicos del cerebro y cerebelo para sueño, mareos, dolores crónicos, fatiga mental y claridad. Técnica craneal avanzada para optimización de funciones cerebrales.',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.acupressure': 'Acupression',
    'nav.breathing': 'Respiration',
    'nav.premium': 'Premium',
    'nav.login': 'Connexion',
    'nav.logout': 'Déconnexion',
    
    // Home Page
    'home.hero.title': 'Transformez votre vie avec les thérapies Wellness',
    'home.hero.subtitle': 'Acupression, respiration 4-7-8, chromothérapie et sons harmonisants dans une plateforme unique',
    'home.hero.startNow': 'Commencer Maintenant',
    'home.hero.createAccount': 'Créer un Compte Gratuit',
    'home.features.title': 'Thérapies Intégrées pour votre Bien-Être',
    'home.features.subtitle': 'Combinez le meilleur de la médecine traditionnelle avec la technologie moderne',
    'home.feature.acupressure.title': 'Acupression Professionnelle',
    'home.feature.acupressure.desc': 'Techniques de MTC adaptées pour le soulagement du stress en milieu professionnel, réduisant les tensions musculaires et l\'anxiété professionnelle',
    'home.feature.cranio.title': 'Crâniothérapie d\'Entreprise',
    'home.feature.cranio.desc': 'Protocoles spécifiques pour le soulagement des céphalées de tension, fatigue mentale et surcharge cognitive liées au travail',
    'home.feature.breathing.title': 'Respiration Anti-Stress',
    'home.feature.breathing.desc': 'Technique 4-7-8 scientifiquement validée pour réduction immédiate de l\'anxiété et régulation du système nerveux pendant les heures de travail',
    'home.feature.chromotherapy.title': 'Chromothérapie Environnementale',
    'home.feature.chromotherapy.desc': 'Application de couleurs thérapeutiques pour optimisation de l\'environnement de travail et réduction des risques psychosociaux',
    'home.feature.sounds.title': 'Paysage Sonore d\'Entreprise',
    'home.feature.sounds.desc': 'Paysages sonores spécialisés pour masquage du bruit professionnel et promotion de la concentration',
    'home.feature.consultation.title': 'Consultation Spécialisée',
    'home.cta.title': 'Votre entreprise promeut-elle la santé intégrale, le Wellness sur le lieu de travail à temps plein?',
    'home.cta.subtitle': 'Implémentez maintenant des pratiques de santé mentale et visez la certification d\'Entreprise Promotrice de la Santé.',
    'home.cta.demo': 'Démonstration Gratuite',
    'home.cta.corporate': 'Consultation d\'Entreprise',
    'home.compliance.title': 'Conformité Légale et Scientifique',
    'home.compliance.subtitle': 'Notre plateforme a été développée en totale conformité avec la législation brésilienne et basée sur des preuves scientifiques reconnues internationalement',
    'home.compliance.law.title': 'Loi 14.831/2024',
    'home.compliance.nr1.title': 'Conformité NR-1',
    'home.wellness.title': 'Quête du Wellness d\'Entreprise',
    'home.wellness.desc': 'Notre méthodologie aide votre entreprise à devenir une Entreprise Promotrice de la Santé Mentale, assistant dans la conformité intégrale aux exigences de la Loi 14.831/2024 et NR-1, avec efficacité en ligne tout au long du processus.',
    
    // Login Page
    'login.welcome': 'Bon retour!',
    'login.createAccount': 'Créer un Compte',
    'login.subtitle.login': 'Connectez-vous à votre compte XZenPress',
    'login.subtitle.register': 'Rejoignez notre communauté de bien-être',
    'login.name': 'Nom Complet',
    'login.email': 'Email',
    'login.password': 'Mot de Passe',
    'login.confirmPassword': 'Confirmer le Mot de Passe',
    'login.forgotPassword': 'Mot de passe oublié?',
    'login.noAccount': 'Pas de compte? En créer un',
    'login.hasAccount': 'Déjà un compte? Se connecter',
    'login.demo.title': 'Pour tester:',
    'login.demo.desc': 'Utilisez n\'importe quel email valide et mot de passe avec 6+ caractères',
    'login.reset.title': 'Réinitialiser le Mot de Passe',
    'login.reset.subtitle': 'Entrez votre email pour recevoir le lien de récupération',
    'login.reset.send': 'Envoyer le Lien de Récupération',
    'login.reset.back': 'Retour à la Connexion',
    
    // Breathing Exercise
    'breathing.title': 'Technique de Respiration 4-7-8',
    'breathing.inhale': 'Inspirer',
    'breathing.hold': 'Retenir',
    'breathing.exhale': 'Expirer',
    'breathing.start': 'Commencer la Session',
    'breathing.stop': 'Arrêter',
    'breathing.reset': 'Reset',
    'breathing.totalTime': 'Temps Total',
    'breathing.chromotherapy.title': 'Chromothérapie Intégrée',
    'breathing.chromotherapy.description': 'Chaque couleur possède des propriétés thérapeutiques spécifiques qui potentialisent les bienfaits de la respiration 4-7-8',
    'breathing.chromotherapy.blue': 'Bleu - Calme et Tranquillité',
    'breathing.chromotherapy.blue.desc': 'Pendant l\'inspiration, le bleu favorise la relaxation profonde et réduit l\'anxiété.',
    'breathing.chromotherapy.green': 'Vert - Équilibre et Harmonie',
    'breathing.chromotherapy.green.desc': 'Pendant la rétention, le vert équilibre le système nerveux et favorise la stabilité émotionnelle.',
    'breathing.chromotherapy.magenta': 'Magenta - Renouveau et Énergie',
    'breathing.chromotherapy.magenta.desc': 'Pendant l\'expiration, le magenta facilite la libération des tensions et renouvelle l\'énergie vitale.',
    'breathing.chromotherapy.blue.short': 'Bleu du Calme',
    'breathing.chromotherapy.green.short': 'Vert de l\'Équilibre',
    'breathing.chromotherapy.magenta.short': 'Magenta du Renouveau',
    'breathing.benefits.title': 'Bénéfices de la Technique 4-7-8',
    'breathing.benefits.stress': 'Réduit stress et anxiété',
    'breathing.benefits.sleep': 'Améliore qualité du sommeil',
    'breathing.benefits.focus': 'Augmente concentration et focus',
    'breathing.benefits.pressure': 'Régule tension artérielle',
    'breathing.sounds.title': 'Sons Harmonisants',
    'breathing.sounds.free.title': 'Sons Gratuits',
    'breathing.sounds.premium.title': 'Sons Premium',
    'breathing.sounds.ocean': 'Sons de l\'Océan',
    'breathing.sounds.ocean.desc': 'Vagues relaxantes de l\'océan',
    'breathing.sounds.rain': 'Pluie Douce',
    'breathing.sounds.rain.desc': 'Son calmant de pluie',
    'breathing.sounds.forest': 'Forêt',
    'breathing.sounds.fireplace': 'Cheminée',
    'breathing.sounds.classical': 'Musique Classique',
    'breathing.sounds.mantras': 'Mantras',
    'breathing.sounds.more': '+ 46 de plus',
    'breathing.sounds.play': 'Jouer',
    'breathing.sounds.pause': 'Pause',
    'breathing.sounds.stop': 'Arrêter Tout',
    'breathing.sounds.premium.desc': 'Débloquez notre bibliothèque complète avec plus de 50 sons relaxants et intégration Spotify Premium',
    'breathing.sounds.premium.upgrade': 'Mettre à Niveau',
    'breathing.sounds.premium.spotify': 'Spotify Premium',
    'breathing.science.title': 'Base Scientifique de la Technique 4-7-8',
    'breathing.science.evidence': 'Preuves Scientifiques',
    'breathing.science.chromotherapy': 'Chromothérapie Scientifique',
    'breathing.science.parasympathetic': 'Active le système nerveux parasympathique',
    'breathing.science.cortisol': 'Réduit le cortisol (hormone du stress)',
    'breathing.science.heartRate': 'Améliore la variabilité de la fréquence cardiaque',
    'breathing.science.gaba': 'Augmente la production de GABA (neurotransmetteur calmant)',
    'breathing.science.blue.effect': 'Bleu: Réduit tension artérielle et fréquence cardiaque',
    'breathing.science.green.effect': 'Vert: Équilibre système nerveux autonome',
    'breathing.science.magenta.effect': 'Magenta: Stimule libération d\'endorphines',
    'breathing.science.melatonin': 'Les couleurs influencent la production de mélatonine',
    'breathing.phase': 'Phase',
    'breathing.phase.inhale.detail': 'Inspiration (4 secondes)',
    'breathing.phase.hold.detail': 'Rétention (7 secondes)',
    'breathing.phase.exhale.detail': 'Expiration (8 secondes)',
    
    // Acupressure Page
    'acupressure.title': 'Acupression et Crâniothérapie',
    'acupressure.subtitle': 'Points thérapeutiques de la Médecine Traditionnelle Chinoise combinés avec la chromothérapie',
    'acupressure.categories.title': 'Catégories de Points',
    'acupressure.category.all': 'Tous les Points',
    'acupressure.category.general': 'MTC (Médecine Traditionnelle Chinoise)',
    'acupressure.category.cranio': 'Crâniopuncture',
    'acupressure.category.septicemia': 'Septicémie',
    'acupressure.category.atm': 'ATM',
    'acupressure.chromotherapy.title': 'Chromothérapie',
    'acupressure.chromotherapy.desc': 'La chromothérapie est automatiquement intégrée au minuteur des points quand activée',
    'acupressure.chromotherapy.manual': 'Chromothérapie Manuelle (1min)',
    'acupressure.chromotherapy.active': 'Chromothérapie Active...',
    'acupressure.chromotherapy.note': 'Utilisez ce bouton seulement pour chromothérapie indépendante',
    'acupressure.points.visual.title': 'Points Thérapeutiques Visuels',
    'acupressure.points.select': 'Sélectionner un Point',
    'acupressure.points.select.desc': 'Cliquez sur n\'importe quel point du diagramme pour voir détails et bénéfices',
    'acupressure.points.free': 'Points Gratuits',
    'acupressure.points.premium': 'Points Premium',
    'acupressure.therapy.integrated': 'Thérapie Intégrée',
    'acupressure.therapy.breathing': 'Respiration Intégrée 4-7-8',
    'acupressure.therapy.start': 'Commencer Acupression + Respiration 4-7-8',
    'acupressure.therapy.stop': 'Arrêter Thérapie Intégrée',
    'acupressure.guide.title': 'Guide d\'Application Intégrée',
    'acupressure.guide.breathing': 'Respiration + Acupression:',
    'acupressure.guide.results': 'Maximisation des Résultats:',
    'acupressure.science.title': 'Science derrière l\'Intégration',
    'acupressure.science.desc': 'La combinaison d\'acupression + respiration 4-7-8 + chromothérapie active simultanément: le système nerveux parasympathique, points d\'acupuncture traditionnels et récepteurs visuels, créant un effet synergique pour relaxation et bien-être maximum.',
    'acupressure.premium.unlock': 'Débloquer Points Spécifiques',
    'acupressure.premium.desc': 'Accédez aux points spécialisés pour septicémie, ATM, crâniothérapie et bien plus',
    'acupressure.premium.upgrade': 'Mise à Niveau Premium',
    'acupressure.stats.title': 'Statistiques de la Plateforme',
    'acupressure.stats.available': 'Points Disponibles',
    'acupressure.stats.free': 'Points Gratuits',
    'acupressure.stats.premium': 'Points Premium',
    'acupressure.stats.categories': 'Catégories',
    'acupressure.tips.title': 'Conseils de Bien-Être',
    'acupressure.tips.morning': 'Routine Matinale',
    'acupressure.tips.sleep': 'Avant de Dormir',
    'acupressure.tips.work': 'Au Travail',
    'acupressure.tips.focus': 'Concentration et Focus',
    'acupressure.safety.title': 'Avis Important',
    'acupressure.safety.desc': 'L\'acupression est une technique complémentaire et ne remplace pas le traitement médical. En cas de conditions graves comme la septicémie, cherchez toujours une assistance médicale professionnelle. Les points premium sont basés sur des techniques traditionnelles et doivent être utilisés comme support au traitement conventionnel.',
    
    // Premium Page
    'premium.title': 'Débloquez Tout le Potentiel',
    'premium.subtitle': 'Accès complet aux consultations spécialisées et ressources thérapeutiques avancées',
    'premium.user.active': 'Utilisateur Premium Actif',
    'premium.upgrade': 'Passer à Premium',
    'premium.features.title': 'Fonctionnalités Premium Disponibles',
    'premium.whatsapp.title': 'Consultation WhatsApp Spécialisée',
    'premium.whatsapp.desc': 'Service direct avec Alexandre Pinheiro - 15 ans d\'expérience',
    'premium.points.title': 'Points d\'Acupression Spécifiques',
    'premium.points.desc': 'Accès aux points spécialisés pour conditions spécifiques',
    'premium.chromotherapy.title': 'Chromothérapie Avancée',
    'premium.chromotherapy.desc': 'Séquences de couleurs personnalisées pour différentes conditions',
    'premium.sounds.title': 'Bibliothèque Complète de Sons',
    'premium.sounds.desc': 'Plus de 50 sons thérapeutiques + intégration Spotify',
    'premium.ai.title': 'Recommandations Personnalisées IA',
    'premium.ai.desc': 'Système intelligent qui apprend de vos habitudes',
    'premium.offline.title': 'Mode Hors Ligne Complet',
    'premium.offline.desc': 'Accès total sans connexion internet',
    'premium.pricing.title': 'Choisissez Votre Plan Premium',
    'premium.pricing.subtitle': 'Investissez dans votre bien-être avec accès complet à toutes les fonctionnalités thérapeutiques',
    'premium.plan.monthly': 'Premium Mensuel',
    'premium.plan.annual': 'Premium Annuel',
    'premium.plan.lifetime': 'Premium à Vie',
    'premium.testimonials.title': 'Ce que disent nos utilisateurs Premium',
    'premium.faq.title': 'Questions Fréquentes',
    'premium.available': 'Disponible',
    'premium.coming.soon': 'Bientôt Disponible',
    'premium.popular': 'Plus Populaire',
    'premium.choose.plan': 'Choisir le Plan',
    
    // WhatsApp Consultation
    'whatsapp.title': 'Consultation Spécialisée',
    'whatsapp.subtitle': 'Pour cas complexes nécessitant attention personnalisée',
    'whatsapp.form.title': 'Formulaire de Consultation',
    'whatsapp.form.subtitle': 'Remplissez les données ci-dessous pour recevoir un service personnalisé via WhatsApp',
    'whatsapp.form.name': 'Nom Complet',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.urgency': 'Niveau d\'Urgence',
    'whatsapp.form.condition': 'Condition Principale',
    'whatsapp.form.duration': 'Depuis combien de temps avez-vous ces symptômes?',
    'whatsapp.form.symptoms': 'Décrivez vos symptômes en détail',
    'whatsapp.form.treatments': 'Traitements déjà effectués',
    'whatsapp.form.medications': 'Médicaments actuels',
    'whatsapp.form.schedule': 'Préférence d\'horaire pour retour',
    'whatsapp.form.send': 'Envoyer via WhatsApp',
    'whatsapp.form.note': 'En envoyant, vous serez redirigé vers WhatsApp avec votre message pré-formaté',
    'whatsapp.important.title': 'Important:',
    'whatsapp.important.desc': 'Ce service ne remplace pas la consultation médicale. En cas d\'urgence, cherchez immédiatement une attention médicale.',
    'whatsapp.back': 'Retour',
    
    // Points data
    'points.yintang.name': 'Yintang (EX-HN3)',
    'points.yintang.desc': 'Situé entre les sourcils, centre du front. Point principal pour réduire stress, anxiété et tension quotidienne.',
    'points.baihui.name': 'Baihui (VG20)',
    'points.baihui.desc': 'Point de rencontre de plusieurs méridiens yang. Approche énergétique MTC pour élever esprit, récupérer conscience et combattre fatigue mentale.',
    'points.cranio.frontal.name': 'Point Frontal Crânien',
    'points.cranio.frontal.desc': 'Situé en région frontale, technique crânienne spécifique pour réduire stress et anxiété par stimulation directe du cortex frontal.',
    'points.cranio.cerebro.name': 'Points Cerveau et Cervelet',
    'points.cranio.cerebro.desc': 'Points spécifiques du cerveau et cervelet pour sommeil, vertiges, douleurs chroniques, fatigue mentale et clarté. Technique crânienne avancée pour optimisation des fonctions cérébrales.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language');
    return languages.find(lang => lang.code === savedLanguage) || languages[0];
  });

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('language', language.code);
  };

  const t = (key: string): string => {
    return translations[currentLanguage.code]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { languages };