import React, { createContext, useContext, useState, useEffect } from 'react';

export interface Language {
  code: string;
  name: string;
  flag: string;
  direction: 'ltr' | 'rtl';
}

export const languages: Language[] = [
  { code: 'pt', name: 'Português', flag: '🇧🇷', direction: 'ltr' },
  { code: 'en', name: 'English', flag: '🇺🇸', direction: 'ltr' },
  { code: 'es', name: 'Español', flag: '🇪🇸', direction: 'ltr' },
  { code: 'zh', name: '中文', flag: '🇨🇳', direction: 'ltr' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳', direction: 'ltr' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', direction: 'rtl' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩', direction: 'ltr' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺', direction: 'ltr' },
  { code: 'ja', name: '日本語', flag: '🇯🇵', direction: 'ltr' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', direction: 'ltr' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', direction: 'ltr' }
];

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Traduções completas para todos os idiomas
const translations: Record<string, Record<string, string>> = {
  pt: {
    // Navegação
    'nav.home': 'Início',
    'nav.acupressure': 'Acupressão',
    'nav.breathing': 'Respiração',
    'nav.premium': 'Premium',
    'nav.corporate': 'Corporativo',
    'nav.dashboard': 'Dashboard',
    'nav.sounds': 'Sons',
    'nav.progress': 'Progresso',
    'nav.personalization': 'Personalização',
    'nav.login': 'Entrar',
    'nav.logout': 'Sair',

    // Home
    'home.hero.title': 'Transforme sua vida com terapias holísticas',
    'home.hero.subtitle': 'Acupressão MTC, respiração 4-7-8, cromoterapia e sons harmonizantes',
    'home.hero.startNow': 'Começar Agora',
    'home.hero.createAccount': 'Criar Conta',
    'home.features.title': 'Recursos Completos',
    'home.features.subtitle': 'Tudo que você precisa para seu bem-estar',
    'home.feature.acupressure.title': 'Acupressão MTC',
    'home.feature.acupressure.desc': '20 pontos terapêuticos da Medicina Tradicional Chinesa',
    'home.feature.cranio.title': 'Craniopuntura',
    'home.feature.cranio.desc': 'Técnicas cranianas para memória, concentração e ansiedade',
    'home.feature.breathing.title': 'Respiração 4-7-8',
    'home.feature.breathing.desc': 'Técnica científica com timer e cromoterapia integrada',
    'home.feature.chromotherapy.title': 'Cromoterapia',
    'home.feature.chromotherapy.desc': 'Cores terapêuticas baseadas em neurociência',
    'home.feature.sounds.title': 'Sons Harmonizantes',
    'home.feature.sounds.desc': 'Biblioteca completa + integração Spotify Premium',
    'home.feature.consultation.title': 'Consultas WhatsApp',
    'home.cta.title': 'Pronto para começar?',
    'home.cta.subtitle': 'Junte-se a milhares de pessoas transformando suas vidas',
    'home.cta.demo': 'Experimentar Grátis',
    'home.cta.corporate': 'Soluções Corporativas',
    'home.compliance.title': 'Compliance Legal Corporativo',
    'home.compliance.subtitle': 'Atendimento integral à legislação brasileira',

    // Login
    'login.welcome': 'Bem-vindo de volta',
    'login.createAccount': 'Criar Conta',
    'login.subtitle.login': 'Entre na sua conta para continuar',
    'login.subtitle.register': 'Crie sua conta e comece sua jornada',
    'login.name': 'Nome Completo',
    'login.email': 'Email',
    'login.password': 'Senha',
    'login.confirmPassword': 'Confirmar Senha',
    'login.forgotPassword': 'Esqueci minha senha',
    'login.noAccount': 'Não tem conta? Criar uma',
    'login.hasAccount': 'Já tem conta? Entrar',
    'login.demo.title': 'Demonstração',
    'login.demo.desc': 'Use qualquer email válido + senha com 6+ caracteres',
    'login.reset.title': 'Recuperar Senha',
    'login.reset.subtitle': 'Digite seu email para receber instruções',
    'login.reset.send': 'Enviar Email',
    'login.reset.back': 'Voltar ao Login',

    // Respiração
    'breathing.title': 'Respiração 4-7-8',
    'breathing.inhale': 'Inspire',
    'breathing.hold': 'Segure',
    'breathing.exhale': 'Expire',
    'breathing.start': 'Iniciar',
    'breathing.stop': 'Parar',
    'breathing.reset': 'Reiniciar',
    'breathing.totalTime': 'Tempo Total',
    'breathing.phase': 'Fase',
    'breathing.phase.inhale.detail': 'Inspiração profunda pelo nariz',
    'breathing.phase.hold.detail': 'Retenção do ar nos pulmões',
    'breathing.phase.exhale.detail': 'Expiração lenta pela boca',
    'breathing.chromotherapy.title': 'Cromoterapia Científica',
    'breathing.chromotherapy.description': 'Cores terapêuticas sincronizadas com cada fase da respiração',
    'breathing.chromotherapy.blue': 'Azul Calmante',
    'breathing.chromotherapy.blue.desc': 'Reduz pressão arterial e ativa o sistema parassimpático',
    'breathing.chromotherapy.blue.short': 'Calmante',
    'breathing.chromotherapy.green': 'Verde Equilibrante',
    'breathing.chromotherapy.green.desc': 'Equilibra o sistema nervoso e harmoniza emoções',
    'breathing.chromotherapy.green.short': 'Equilibrante',
    'breathing.chromotherapy.magenta': 'Roxo Energizante',
    'breathing.chromotherapy.magenta.desc': 'Estimula a produção de endorfinas e libera tensões',
    'breathing.chromotherapy.magenta.short': 'Energizante',
    'breathing.benefits.title': 'Benefícios Científicos',
    'breathing.benefits.stress': 'Reduz cortisol',
    'breathing.benefits.sleep': 'Melhora sono',
    'breathing.benefits.focus': 'Aumenta foco',
    'breathing.benefits.pressure': 'Reduz pressão',
    'breathing.science.title': 'Base Científica',
    'breathing.science.evidence': 'Evidências Científicas',
    'breathing.science.parasympathetic': 'Ativa sistema parassimpático',
    'breathing.science.cortisol': 'Reduz cortisol em 23%',
    'breathing.science.heartRate': 'Diminui frequência cardíaca',
    'breathing.science.gaba': 'Aumenta GABA cerebral',
    'breathing.science.chromotherapy': 'Cromoterapia',
    'breathing.science.blue.effect': 'Azul reduz pressão arterial',
    'breathing.science.green.effect': 'Verde equilibra sistema nervoso',
    'breathing.science.magenta.effect': 'Roxo estimula endorfinas',
    'breathing.science.melatonin': 'Cores regulam melatonina',
    'breathing.sounds.title': 'Sons Harmonizantes',
    'breathing.sounds.free.title': 'Sons Gratuitos',
    'breathing.sounds.ocean': 'Sons do Mar',
    'breathing.sounds.ocean.desc': 'Ondas relaxantes',
    'breathing.sounds.rain': 'Chuva Suave',
    'breathing.sounds.rain.desc': 'Chuva calmante',
    'breathing.sounds.forest': 'Floresta',
    'breathing.sounds.fireplace': 'Lareira',
    'breathing.sounds.classical': 'Clássica',
    'breathing.sounds.mantras': 'Mantras',
    'breathing.sounds.more': '+45 sons',
    'breathing.sounds.play': 'Reproduzir',
    'breathing.sounds.pause': 'Pausar',
    'breathing.sounds.stop': 'Parar',
    'breathing.sounds.premium.title': 'Biblioteca Premium',
    'breathing.sounds.premium.desc': 'Mais de 50 sons exclusivos + integração Spotify',
    'breathing.sounds.premium.spotify': 'Abrir Spotify',
    'breathing.sounds.premium.upgrade': 'Upgrade Premium',

    // Premium
    'premium.hero.title': 'Desbloqueie Todo o Potencial',
    'premium.hero.subtitle': 'Acesso completo a consultas especializadas e pontos exclusivos',
    'premium.hero.active': 'Premium Ativo',
    'premium.hero.upgrade': 'Fazer Upgrade',
    'premium.features.title': 'Recursos Premium',
    'premium.features.available': 'Disponível',
    'premium.features.coming': 'Em Breve',
    'premium.features.whatsapp.title': 'Consultas WhatsApp',
    'premium.features.whatsapp.description': 'Atendimento especializado via WhatsApp',
    'premium.features.whatsapp.benefit1': 'Profissional com 15+ anos',
    'premium.features.whatsapp.benefit2': 'Resposta em até 2h',
    'premium.features.whatsapp.benefit3': 'Casos complexos',
    'premium.features.whatsapp.benefit4': 'Acompanhamento personalizado',
    'premium.features.points.title': 'Pontos Exclusivos',
    'premium.features.points.description': '11 pontos especializados premium',
    'premium.features.points.benefit1': 'Septicemia (3 pontos)',
    'premium.features.points.benefit2': 'ATM (3 pontos)',
    'premium.features.points.benefit3': 'Cranioterapia (3 pontos)',
    'premium.features.points.benefit4': 'Neurologia (2 pontos)',
    'premium.features.chromotherapy.title': 'Cromoterapia Avançada',
    'premium.features.chromotherapy.description': 'Sequências personalizadas de cores',
    'premium.features.chromotherapy.benefit1': 'Perfis adaptativos',
    'premium.features.chromotherapy.benefit2': 'Sincronização biofeedback',
    'premium.features.chromotherapy.benefit3': 'Cores personalizadas',
    'premium.features.chromotherapy.benefit4': 'Terapia integrada',
    'premium.features.sounds.title': 'Biblioteca Completa',
    'premium.features.sounds.description': '50+ sons + Spotify Premium',
    'premium.features.sounds.benefit1': 'Frequências binaurais',
    'premium.features.sounds.benefit2': 'Mantras sagrados',
    'premium.features.sounds.benefit3': 'Natureza HD',
    'premium.features.sounds.benefit4': 'Playlists curadas',
    'premium.features.ai.title': 'Recomendações IA',
    'premium.features.ai.description': 'Inteligência artificial personalizada',
    'premium.features.ai.benefit1': 'Análise de padrões',
    'premium.features.ai.benefit2': 'Sugestões personalizadas',
    'premium.features.ai.benefit3': 'Otimização automática',
    'premium.features.ai.benefit4': 'Insights preditivos',
    'premium.features.offline.title': 'Modo Offline',
    'premium.features.offline.description': 'Funcionalidades offline completas',
    'premium.features.offline.benefit1': 'Sincronização automática',
    'premium.features.offline.benefit2': 'Cache inteligente',
    'premium.features.offline.benefit3': 'Dados seguros',
    'premium.features.offline.benefit4': 'Acesso sem internet',
    'premium.plans.title': 'Planos Premium',
    'premium.plans.subtitle': 'Escolha o plano ideal para você',
    'premium.plans.popular': 'Mais Popular',
    'premium.plans.choose': 'Escolher Plano',
    'premium.plans.save': 'Economize',
    'premium.plans.monthly.name': 'Premium Mensal',
    'premium.plans.monthly.period': '/mês',
    'premium.plans.monthly.feature1': 'Consultas WhatsApp ilimitadas',
    'premium.plans.monthly.feature2': '11 pontos exclusivos',
    'premium.plans.monthly.feature3': 'Biblioteca completa de sons',
    'premium.plans.monthly.feature4': 'Cromoterapia avançada',
    'premium.plans.monthly.feature5': 'Suporte prioritário',
    'premium.plans.annual.name': 'Premium Anual',
    'premium.plans.annual.period': '/ano',
    'premium.plans.annual.feature1': 'Tudo do plano mensal',
    'premium.plans.annual.feature2': '2 meses grátis',
    'premium.plans.annual.feature3': 'Recomendações IA',
    'premium.plans.annual.feature4': 'Relatórios avançados',
    'premium.plans.annual.feature5': 'Acesso beta a novos recursos',
    'premium.plans.lifetime.name': 'Premium Vitalício',
    'premium.plans.lifetime.period': 'pagamento único',
    'premium.plans.lifetime.feature1': 'Acesso vitalício completo',
    'premium.plans.lifetime.feature2': 'Todos os recursos futuros',
    'premium.plans.lifetime.feature3': 'Suporte VIP',
    'premium.plans.lifetime.feature4': 'Consultoria personalizada',
    'premium.plans.lifetime.feature5': 'Sem mensalidades',
    'premium.payment.title': 'Finalizar Pagamento',
    'premium.payment.methods': 'Métodos de Pagamento',
    'premium.payment.pix': 'PIX',
    'premium.payment.pix.desc': 'Instantâneo',
    'premium.payment.pix.title': 'Pagamento via PIX',
    'premium.payment.credit': 'Cartão',
    'premium.payment.credit.desc': 'Visa, Master, Amex',
    'premium.payment.credit.title': 'Cartão de Crédito',
    'premium.payment.crypto': 'Crypto',
    'premium.payment.crypto.desc': 'Bitcoin, Ethereum',
    'premium.payment.crypto.title': 'Criptomoedas',
    'premium.payment.back': 'Voltar',
    'premium.payment.confirm': 'Confirmar Pagamento',
    'premium.testimonials.title': 'Depoimentos',
    'premium.testimonials.maria': 'Atendimento excepcional! Resolveu minha dor crônica em poucas sessões.',
    'premium.testimonials.joao': 'A plataforma mudou minha vida. Durmo melhor e tenho menos ansiedade.',
    'premium.testimonials.ana': 'Profissional muito competente. Recomendo para todos!',
    'premium.faq.title': 'Perguntas Frequentes',
    'premium.faq.q1': 'Como funciona o atendimento WhatsApp?',
    'premium.faq.a1': 'Você preenche um formulário detalhado e recebe atendimento personalizado via WhatsApp.',
    'premium.faq.q2': 'Posso cancelar a qualquer momento?',
    'premium.faq.a2': 'Sim, você pode cancelar sua assinatura a qualquer momento sem taxas.',
    'premium.faq.q3': 'Os pontos premium são seguros?',
    'premium.faq.a3': 'Todos os pontos são baseados na Medicina Tradicional Chinesa com supervisão profissional.',
    'premium.faq.q4': 'Quanto tempo para ver resultados?',
    'premium.faq.a4': 'A maioria dos usuários relata melhoras em 1-2 semanas de uso regular.',

    // WhatsApp
    'whatsapp.back': 'Voltar',
    'whatsapp.consultation.title': 'Consulta Especializada',
    'whatsapp.consultation.description': 'Atendimento personalizado para casos complexos',
    'whatsapp.features.specialized.title': 'Atendimento Especializado',
    'whatsapp.features.specialized.subtitle': 'Profissional qualificado',
    'whatsapp.features.specialized.professional': '15+ anos de experiência',
    'whatsapp.features.fast.title': 'Resposta Rápida',
    'whatsapp.features.fast.subtitle': 'Até 2 horas',
    'whatsapp.features.direct.title': 'WhatsApp Direto',
    'whatsapp.features.direct.subtitle': 'Comunicação direta',
    'whatsapp.when.title': 'Quando buscar ajuda:',
    'whatsapp.when.chronic': 'Dores crônicas persistentes',
    'whatsapp.when.neurological': 'Problemas neurológicos',
    'whatsapp.when.nonresponsive': 'Casos não responsivos',
    'whatsapp.when.personalized': 'Tratamento personalizado',
    'whatsapp.testimonial.text': 'Atendimento excepcional! Resolveu minha dor crônica em poucas sessões.',
    'whatsapp.testimonial.author': 'Maria S., São Paulo',
    'whatsapp.form.title': 'Formulário de Consulta',
    'whatsapp.form.subtitle': 'Preencha os dados para atendimento personalizado',
    'whatsapp.form.name': 'Nome Completo',
    'whatsapp.form.name.placeholder': 'Seu nome completo',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.email.placeholder': 'seu@email.com',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.whatsapp.placeholder': '(11) 99999-9999',
    'whatsapp.form.urgency': 'Urgência',
    'whatsapp.form.urgency.select': 'Selecione a urgência',
    'whatsapp.form.urgency.low': 'Baixa - Consulta de rotina',
    'whatsapp.form.urgency.medium': 'Média - Desconforto moderado',
    'whatsapp.form.urgency.high': 'Alta - Dor intensa',
    'whatsapp.form.urgency.urgent': 'Urgente - Necessita atenção imediata',
    'whatsapp.form.medical.title': 'Informações Médicas',
    'whatsapp.form.medical.condition': 'Condição Principal',
    'whatsapp.form.medical.condition.placeholder': 'Ex: Dor de cabeça crônica, ansiedade, insônia...',
    'whatsapp.form.medical.duration': 'Há quanto tempo tem os sintomas?',
    'whatsapp.form.medical.duration.placeholder': 'Ex: 2 meses, 1 ano...',
    'whatsapp.form.medical.symptoms': 'Descrição Detalhada dos Sintomas',
    'whatsapp.form.medical.symptoms.placeholder': 'Descreva em detalhes seus sintomas, quando ocorrem, intensidade...',
    'whatsapp.form.medical.treatments': 'Tratamentos Já Realizados',
    'whatsapp.form.medical.treatments.placeholder': 'Medicamentos, terapias, cirurgias...',
    'whatsapp.form.medical.medications': 'Medicamentos Atuais',
    'whatsapp.form.medical.medications.placeholder': 'Liste todos os medicamentos que usa atualmente...',
    'whatsapp.form.medical.schedule': 'Horário de Preferência',
    'whatsapp.form.medical.schedule.select': 'Selecione o melhor horário',
    'whatsapp.form.medical.schedule.morning': 'Manhã (8h-12h)',
    'whatsapp.form.medical.schedule.afternoon': 'Tarde (12h-18h)',
    'whatsapp.form.medical.schedule.evening': 'Noite (18h-22h)',
    'whatsapp.form.medical.schedule.anytime': 'Qualquer horário',
    'whatsapp.form.notice.title': 'Importante:',
    'whatsapp.form.notice.text': 'Este formulário será enviado diretamente para nosso especialista via WhatsApp.',
    'whatsapp.form.submit': 'Enviar para WhatsApp',
    'whatsapp.form.redirect': 'Você será redirecionado para o WhatsApp'
  },

  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.acupressure': 'Acupressure',
    'nav.breathing': 'Breathing',
    'nav.premium': 'Premium',
    'nav.corporate': 'Corporate',
    'nav.dashboard': 'Dashboard',
    'nav.sounds': 'Sounds',
    'nav.progress': 'Progress',
    'nav.personalization': 'Personalization',
    'nav.login': 'Login',
    'nav.logout': 'Logout',

    // Home
    'home.hero.title': 'Transform your life with holistic therapies',
    'home.hero.subtitle': 'TCM acupressure, 4-7-8 breathing, chromotherapy and harmonizing sounds',
    'home.hero.startNow': 'Start Now',
    'home.hero.createAccount': 'Create Account',
    'home.features.title': 'Complete Features',
    'home.features.subtitle': 'Everything you need for your wellness',
    'home.feature.acupressure.title': 'TCM Acupressure',
    'home.feature.acupressure.desc': '20 therapeutic points from Traditional Chinese Medicine',
    'home.feature.cranio.title': 'Craniopuncture',
    'home.feature.cranio.desc': 'Cranial techniques for memory, concentration and anxiety',
    'home.feature.breathing.title': '4-7-8 Breathing',
    'home.feature.breathing.desc': 'Scientific technique with timer and integrated chromotherapy',
    'home.feature.chromotherapy.title': 'Chromotherapy',
    'home.feature.chromotherapy.desc': 'Therapeutic colors based on neuroscience',
    'home.feature.sounds.title': 'Harmonizing Sounds',
    'home.feature.sounds.desc': 'Complete library + Spotify Premium integration',
    'home.feature.consultation.title': 'WhatsApp Consultations',
    'home.cta.title': 'Ready to start?',
    'home.cta.subtitle': 'Join thousands of people transforming their lives',
    'home.cta.demo': 'Try Free',
    'home.cta.corporate': 'Corporate Solutions',
    'home.compliance.title': 'Corporate Legal Compliance',
    'home.compliance.subtitle': 'Full compliance with Brazilian legislation',

    // Login
    'login.welcome': 'Welcome back',
    'login.createAccount': 'Create Account',
    'login.subtitle.login': 'Sign in to your account to continue',
    'login.subtitle.register': 'Create your account and start your journey',
    'login.name': 'Full Name',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.confirmPassword': 'Confirm Password',
    'login.forgotPassword': 'Forgot password',
    'login.noAccount': 'No account? Create one',
    'login.hasAccount': 'Already have account? Sign in',
    'login.demo.title': 'Demo',
    'login.demo.desc': 'Use any valid email + password with 6+ characters',
    'login.reset.title': 'Reset Password',
    'login.reset.subtitle': 'Enter your email to receive instructions',
    'login.reset.send': 'Send Email',
    'login.reset.back': 'Back to Login',

    // Breathing
    'breathing.title': '4-7-8 Breathing',
    'breathing.inhale': 'Inhale',
    'breathing.hold': 'Hold',
    'breathing.exhale': 'Exhale',
    'breathing.start': 'Start',
    'breathing.stop': 'Stop',
    'breathing.reset': 'Reset',
    'breathing.totalTime': 'Total Time',
    'breathing.phase': 'Phase',
    'breathing.phase.inhale.detail': 'Deep inhalation through nose',
    'breathing.phase.hold.detail': 'Hold air in lungs',
    'breathing.phase.exhale.detail': 'Slow exhalation through mouth',
    'breathing.chromotherapy.title': 'Scientific Chromotherapy',
    'breathing.chromotherapy.description': 'Therapeutic colors synchronized with each breathing phase',
    'breathing.chromotherapy.blue': 'Calming Blue',
    'breathing.chromotherapy.blue.desc': 'Reduces blood pressure and activates parasympathetic system',
    'breathing.chromotherapy.blue.short': 'Calming',
    'breathing.chromotherapy.green': 'Balancing Green',
    'breathing.chromotherapy.green.desc': 'Balances nervous system and harmonizes emotions',
    'breathing.chromotherapy.green.short': 'Balancing',
    'breathing.chromotherapy.magenta': 'Energizing Purple',
    'breathing.chromotherapy.magenta.desc': 'Stimulates endorphin production and releases tension',
    'breathing.chromotherapy.magenta.short': 'Energizing',
    'breathing.benefits.title': 'Scientific Benefits',
    'breathing.benefits.stress': 'Reduces cortisol',
    'breathing.benefits.sleep': 'Improves sleep',
    'breathing.benefits.focus': 'Increases focus',
    'breathing.benefits.pressure': 'Reduces pressure',
    'breathing.science.title': 'Scientific Foundation',
    'breathing.science.evidence': 'Scientific Evidence',
    'breathing.science.parasympathetic': 'Activates parasympathetic system',
    'breathing.science.cortisol': 'Reduces cortisol by 23%',
    'breathing.science.heartRate': 'Decreases heart rate',
    'breathing.science.gaba': 'Increases brain GABA',
    'breathing.science.chromotherapy': 'Chromotherapy',
    'breathing.science.blue.effect': 'Blue reduces blood pressure',
    'breathing.science.green.effect': 'Green balances nervous system',
    'breathing.science.magenta.effect': 'Purple stimulates endorphins',
    'breathing.science.melatonin': 'Colors regulate melatonin',
    'breathing.sounds.title': 'Harmonizing Sounds',
    'breathing.sounds.free.title': 'Free Sounds',
    'breathing.sounds.ocean': 'Ocean Sounds',
    'breathing.sounds.ocean.desc': 'Relaxing waves',
    'breathing.sounds.rain': 'Gentle Rain',
    'breathing.sounds.rain.desc': 'Calming rain',
    'breathing.sounds.forest': 'Forest',
    'breathing.sounds.fireplace': 'Fireplace',
    'breathing.sounds.classical': 'Classical',
    'breathing.sounds.mantras': 'Mantras',
    'breathing.sounds.more': '+45 sounds',
    'breathing.sounds.play': 'Play',
    'breathing.sounds.pause': 'Pause',
    'breathing.sounds.stop': 'Stop',
    'breathing.sounds.premium.title': 'Premium Library',
    'breathing.sounds.premium.desc': 'Over 50 exclusive sounds + Spotify integration',
    'breathing.sounds.premium.spotify': 'Open Spotify',
    'breathing.sounds.premium.upgrade': 'Upgrade Premium',

    // Premium
    'premium.hero.title': 'Unlock Full Potential',
    'premium.hero.subtitle': 'Complete access to specialized consultations and exclusive points',
    'premium.hero.active': 'Premium Active',
    'premium.hero.upgrade': 'Upgrade',
    'premium.features.title': 'Premium Features',
    'premium.features.available': 'Available',
    'premium.features.coming': 'Coming Soon',
    'premium.features.whatsapp.title': 'WhatsApp Consultations',
    'premium.features.whatsapp.description': 'Specialized care via WhatsApp',
    'premium.features.whatsapp.benefit1': 'Professional with 15+ years',
    'premium.features.whatsapp.benefit2': 'Response within 2h',
    'premium.features.whatsapp.benefit3': 'Complex cases',
    'premium.features.whatsapp.benefit4': 'Personalized follow-up',
    'premium.features.points.title': 'Exclusive Points',
    'premium.features.points.description': '11 specialized premium points',
    'premium.features.points.benefit1': 'Septicemia (3 points)',
    'premium.features.points.benefit2': 'TMJ (3 points)',
    'premium.features.points.benefit3': 'Craniotherapy (3 points)',
    'premium.features.points.benefit4': 'Neurology (2 points)',
    'premium.features.chromotherapy.title': 'Advanced Chromotherapy',
    'premium.features.chromotherapy.description': 'Personalized color sequences',
    'premium.features.chromotherapy.benefit1': 'Adaptive profiles',
    'premium.features.chromotherapy.benefit2': 'Biofeedback sync',
    'premium.features.chromotherapy.benefit3': 'Custom colors',
    'premium.features.chromotherapy.benefit4': 'Integrated therapy',
    'premium.features.sounds.title': 'Complete Library',
    'premium.features.sounds.description': '50+ sounds + Spotify Premium',
    'premium.features.sounds.benefit1': 'Binaural frequencies',
    'premium.features.sounds.benefit2': 'Sacred mantras',
    'premium.features.sounds.benefit3': 'Nature HD',
    'premium.features.sounds.benefit4': 'Curated playlists',
    'premium.features.ai.title': 'AI Recommendations',
    'premium.features.ai.description': 'Personalized artificial intelligence',
    'premium.features.ai.benefit1': 'Pattern analysis',
    'premium.features.ai.benefit2': 'Personalized suggestions',
    'premium.features.ai.benefit3': 'Automatic optimization',
    'premium.features.ai.benefit4': 'Predictive insights',
    'premium.features.offline.title': 'Offline Mode',
    'premium.features.offline.description': 'Complete offline functionality',
    'premium.features.offline.benefit1': 'Automatic sync',
    'premium.features.offline.benefit2': 'Smart cache',
    'premium.features.offline.benefit3': 'Secure data',
    'premium.features.offline.benefit4': 'No internet access',
    'premium.plans.title': 'Premium Plans',
    'premium.plans.subtitle': 'Choose the ideal plan for you',
    'premium.plans.popular': 'Most Popular',
    'premium.plans.choose': 'Choose Plan',
    'premium.plans.save': 'Save',
    'premium.plans.monthly.name': 'Monthly Premium',
    'premium.plans.monthly.period': '/month',
    'premium.plans.monthly.feature1': 'Unlimited WhatsApp consultations',
    'premium.plans.monthly.feature2': '11 exclusive points',
    'premium.plans.monthly.feature3': 'Complete sound library',
    'premium.plans.monthly.feature4': 'Advanced chromotherapy',
    'premium.plans.monthly.feature5': 'Priority support',
    'premium.plans.annual.name': 'Annual Premium',
    'premium.plans.annual.period': '/year',
    'premium.plans.annual.feature1': 'Everything from monthly plan',
    'premium.plans.annual.feature2': '2 months free',
    'premium.plans.annual.feature3': 'AI recommendations',
    'premium.plans.annual.feature4': 'Advanced reports',
    'premium.plans.annual.feature5': 'Beta access to new features',
    'premium.plans.lifetime.name': 'Lifetime Premium',
    'premium.plans.lifetime.period': 'one-time payment',
    'premium.plans.lifetime.feature1': 'Complete lifetime access',
    'premium.plans.lifetime.feature2': 'All future features',
    'premium.plans.lifetime.feature3': 'VIP support',
    'premium.plans.lifetime.feature4': 'Personalized consulting',
    'premium.plans.lifetime.feature5': 'No monthly fees',
    'premium.payment.title': 'Complete Payment',
    'premium.payment.methods': 'Payment Methods',
    'premium.payment.pix': 'PIX',
    'premium.payment.pix.desc': 'Instant',
    'premium.payment.pix.title': 'PIX Payment',
    'premium.payment.credit': 'Card',
    'premium.payment.credit.desc': 'Visa, Master, Amex',
    'premium.payment.credit.title': 'Credit Card',
    'premium.payment.crypto': 'Crypto',
    'premium.payment.crypto.desc': 'Bitcoin, Ethereum',
    'premium.payment.crypto.title': 'Cryptocurrencies',
    'premium.payment.back': 'Back',
    'premium.payment.confirm': 'Confirm Payment',
    'premium.testimonials.title': 'Testimonials',
    'premium.testimonials.maria': 'Exceptional service! Solved my chronic pain in just a few sessions.',
    'premium.testimonials.joao': 'The platform changed my life. I sleep better and have less anxiety.',
    'premium.testimonials.ana': 'Very competent professional. I recommend it to everyone!',
    'premium.faq.title': 'Frequently Asked Questions',
    'premium.faq.q1': 'How does WhatsApp service work?',
    'premium.faq.a1': 'You fill out a detailed form and receive personalized care via WhatsApp.',
    'premium.faq.q2': 'Can I cancel anytime?',
    'premium.faq.a2': 'Yes, you can cancel your subscription anytime without fees.',
    'premium.faq.q3': 'Are premium points safe?',
    'premium.faq.a3': 'All points are based on Traditional Chinese Medicine with professional supervision.',
    'premium.faq.q4': 'How long to see results?',
    'premium.faq.a4': 'Most users report improvements within 1-2 weeks of regular use.',

    // WhatsApp
    'whatsapp.back': 'Back',
    'whatsapp.consultation.title': 'Specialized Consultation',
    'whatsapp.consultation.description': 'Personalized care for complex cases',
    'whatsapp.features.specialized.title': 'Specialized Care',
    'whatsapp.features.specialized.subtitle': 'Qualified professional',
    'whatsapp.features.specialized.professional': '15+ years experience',
    'whatsapp.features.fast.title': 'Fast Response',
    'whatsapp.features.fast.subtitle': 'Within 2 hours',
    'whatsapp.features.direct.title': 'Direct WhatsApp',
    'whatsapp.features.direct.subtitle': 'Direct communication',
    'whatsapp.when.title': 'When to seek help:',
    'whatsapp.when.chronic': 'Persistent chronic pain',
    'whatsapp.when.neurological': 'Neurological problems',
    'whatsapp.when.nonresponsive': 'Non-responsive cases',
    'whatsapp.when.personalized': 'Personalized treatment',
    'whatsapp.testimonial.text': 'Exceptional service! Solved my chronic pain in just a few sessions.',
    'whatsapp.testimonial.author': 'Maria S., São Paulo',
    'whatsapp.form.title': 'Consultation Form',
    'whatsapp.form.subtitle': 'Fill in the details for personalized care',
    'whatsapp.form.name': 'Full Name',
    'whatsapp.form.name.placeholder': 'Your full name',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.email.placeholder': 'your@email.com',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.whatsapp.placeholder': '+1 (555) 123-4567',
    'whatsapp.form.urgency': 'Urgency',
    'whatsapp.form.urgency.select': 'Select urgency',
    'whatsapp.form.urgency.low': 'Low - Routine consultation',
    'whatsapp.form.urgency.medium': 'Medium - Moderate discomfort',
    'whatsapp.form.urgency.high': 'High - Intense pain',
    'whatsapp.form.urgency.urgent': 'Urgent - Needs immediate attention',
    'whatsapp.form.medical.title': 'Medical Information',
    'whatsapp.form.medical.condition': 'Main Condition',
    'whatsapp.form.medical.condition.placeholder': 'Ex: Chronic headache, anxiety, insomnia...',
    'whatsapp.form.medical.duration': 'How long have you had symptoms?',
    'whatsapp.form.medical.duration.placeholder': 'Ex: 2 months, 1 year...',
    'whatsapp.form.medical.symptoms': 'Detailed Symptom Description',
    'whatsapp.form.medical.symptoms.placeholder': 'Describe your symptoms in detail, when they occur, intensity...',
    'whatsapp.form.medical.treatments': 'Previous Treatments',
    'whatsapp.form.medical.treatments.placeholder': 'Medications, therapies, surgeries...',
    'whatsapp.form.medical.medications': 'Current Medications',
    'whatsapp.form.medical.medications.placeholder': 'List all medications you currently use...',
    'whatsapp.form.medical.schedule': 'Preferred Time',
    'whatsapp.form.medical.schedule.select': 'Select best time',
    'whatsapp.form.medical.schedule.morning': 'Morning (8am-12pm)',
    'whatsapp.form.medical.schedule.afternoon': 'Afternoon (12pm-6pm)',
    'whatsapp.form.medical.schedule.evening': 'Evening (6pm-10pm)',
    'whatsapp.form.medical.schedule.anytime': 'Anytime',
    'whatsapp.form.notice.title': 'Important:',
    'whatsapp.form.notice.text': 'This form will be sent directly to our specialist via WhatsApp.',
    'whatsapp.form.submit': 'Send to WhatsApp',
    'whatsapp.form.redirect': 'You will be redirected to WhatsApp'
  },

  es: {
    // Navegación
    'nav.home': 'Inicio',
    'nav.acupressure': 'Acupresión',
    'nav.breathing': 'Respiración',
    'nav.premium': 'Premium',
    'nav.corporate': 'Corporativo',
    'nav.dashboard': 'Panel',
    'nav.sounds': 'Sonidos',
    'nav.progress': 'Progreso',
    'nav.personalization': 'Personalización',
    'nav.login': 'Entrar',
    'nav.logout': 'Salir',

    // Inicio
    'home.hero.title': 'Transforma tu vida con terapias holísticas',
    'home.hero.subtitle': 'Acupresión MTC, respiración 4-7-8, cromoterapia y sonidos armonizantes',
    'home.hero.startNow': 'Comenzar Ahora',
    'home.hero.createAccount': 'Crear Cuenta',
    'home.features.title': 'Características Completas',
    'home.features.subtitle': 'Todo lo que necesitas para tu bienestar',
    'home.feature.acupressure.title': 'Acupresión MTC',
    'home.feature.acupressure.desc': '20 puntos terapéuticos de Medicina Tradicional China',
    'home.feature.cranio.title': 'Craniopuntura',
    'home.feature.cranio.desc': 'Técnicas craneales para memoria, concentración y ansiedad',
    'home.feature.breathing.title': 'Respiración 4-7-8',
    'home.feature.breathing.desc': 'Técnica científica con temporizador y cromoterapia integrada',
    'home.feature.chromotherapy.title': 'Cromoterapia',
    'home.feature.chromotherapy.desc': 'Colores terapéuticos basados en neurociencia',
    'home.feature.sounds.title': 'Sonidos Armonizantes',
    'home.feature.sounds.desc': 'Biblioteca completa + integración Spotify Premium',
    'home.feature.consultation.title': 'Consultas WhatsApp',
    'home.cta.title': '¿Listo para comenzar?',
    'home.cta.subtitle': 'Únete a miles de personas transformando sus vidas',
    'home.cta.demo': 'Probar Gratis',
    'home.cta.corporate': 'Soluciones Corporativas',
    'home.compliance.title': 'Cumplimiento Legal Corporativo',
    'home.compliance.subtitle': 'Cumplimiento integral con legislación brasileña'
  },

  zh: {
    // 导航
    'nav.home': '首页',
    'nav.acupressure': '穴位按摩',
    'nav.breathing': '呼吸',
    'nav.premium': '高级版',
    'nav.corporate': '企业版',
    'nav.dashboard': '仪表板',
    'nav.sounds': '声音',
    'nav.progress': '进度',
    'nav.personalization': '个性化',
    'nav.login': '登录',
    'nav.logout': '退出',

    // 首页
    'home.hero.title': '用整体疗法改变你的生活',
    'home.hero.subtitle': '中医穴位按摩、4-7-8呼吸法、色彩疗法和和谐音效',
    'home.hero.startNow': '立即开始',
    'home.hero.createAccount': '创建账户',
    'home.features.title': '完整功能',
    'home.features.subtitle': '您健康所需的一切',
    'home.feature.acupressure.title': '中医穴位按摩',
    'home.feature.acupressure.desc': '20个传统中医治疗穴位',
    'home.feature.cranio.title': '头针疗法',
    'home.feature.cranio.desc': '针对记忆、专注力和焦虑的头部技术',
    'home.feature.breathing.title': '4-7-8呼吸法',
    'home.feature.breathing.desc': '科学技术配合计时器和综合色彩疗法',
    'home.feature.chromotherapy.title': '色彩疗法',
    'home.feature.chromotherapy.desc': '基于神经科学的治疗色彩',
    'home.feature.sounds.title': '和谐音效',
    'home.feature.sounds.desc': '完整音库 + Spotify Premium集成',
    'home.feature.consultation.title': 'WhatsApp咨询',
    'home.cta.title': '准备开始了吗？',
    'home.cta.subtitle': '加入数千人改变生活的行列',
    'home.cta.demo': '免费试用',
    'home.cta.corporate': '企业解决方案',
    'home.compliance.title': '企业法律合规',
    'home.compliance.subtitle': '全面符合巴西法律'
  },

  hi: {
    // नेवीगेशन
    'nav.home': 'होम',
    'nav.acupressure': 'एक्यूप्रेशर',
    'nav.breathing': 'श्वास',
    'nav.premium': 'प्रीमियम',
    'nav.corporate': 'कॉर्पोरेट',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.sounds': 'ध्वनि',
    'nav.progress': 'प्रगति',
    'nav.personalization': 'व्यक्तिगतकरण',
    'nav.login': 'लॉगिन',
    'nav.logout': 'लॉगआउट',

    // होम
    'home.hero.title': 'समग्र चिकित्सा से अपना जीवन बदलें',
    'home.hero.subtitle': 'TCM एक्यूप्रेशर, 4-7-8 श्वास, रंग चिकित्सा और सामंजस्यपूर्ण ध्वनियां',
    'home.hero.startNow': 'अभी शुरू करें',
    'home.hero.createAccount': 'खाता बनाएं',
    'home.features.title': 'पूर्ण सुविधाएं',
    'home.features.subtitle': 'आपकी भलाई के लिए आवश्यक सब कुछ',
    'home.feature.acupressure.title': 'TCM एक्यूप्रेशर',
    'home.feature.acupressure.desc': 'पारंपरिक चीनी चिकित्सा के 20 चिकित्सीय बिंदु',
    'home.feature.cranio.title': 'क्रेनियोपंक्चर',
    'home.feature.cranio.desc': 'स्मृति, एकाग्रता और चिंता के लिए कपाल तकनीक',
    'home.feature.breathing.title': '4-7-8 श्वास',
    'home.feature.breathing.desc': 'टाइमर और एकीकृत रंग चिकित्सा के साथ वैज्ञानिक तकनीक',
    'home.feature.chromotherapy.title': 'रंग चिकित्सा',
    'home.feature.chromotherapy.desc': 'न्यूरोसाइंस पर आधारित चिकित्सीय रंग',
    'home.feature.sounds.title': 'सामंजस्यपूर्ण ध्वनियां',
    'home.feature.sounds.desc': 'पूर्ण लाइब्रेरी + Spotify Premium एकीकरण',
    'home.feature.consultation.title': 'WhatsApp परामर्श',
    'home.cta.title': 'शुरू करने के लिए तैयार?',
    'home.cta.subtitle': 'हजारों लोगों के साथ जुड़ें जो अपना जीवन बदल रहे हैं',
    'home.cta.demo': 'मुफ्त आज़माएं',
    'home.cta.corporate': 'कॉर्पोरेट समाधान',
    'home.compliance.title': 'कॉर्पोरेट कानूनी अनुपालन',
    'home.compliance.subtitle': 'ब्राजीलियाई कानून के साथ पूर्ण अनुपालन'
  },

  ar: {
    // التنقل
    'nav.home': 'الرئيسية',
    'nav.acupressure': 'العلاج بالضغط',
    'nav.breathing': 'التنفس',
    'nav.premium': 'المميز',
    'nav.corporate': 'الشركات',
    'nav.dashboard': 'لوحة التحكم',
    'nav.sounds': 'الأصوات',
    'nav.progress': 'التقدم',
    'nav.personalization': 'التخصيص',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل الخروج',

    // الرئيسية
    'home.hero.title': 'حول حياتك بالعلاجات الشاملة',
    'home.hero.subtitle': 'العلاج بالضغط الصيني، تنفس 4-7-8، العلاج بالألوان والأصوات المتناغمة',
    'home.hero.startNow': 'ابدأ الآن',
    'home.hero.createAccount': 'إنشاء حساب',
    'home.features.title': 'ميزات كاملة',
    'home.features.subtitle': 'كل ما تحتاجه لصحتك',
    'home.feature.acupressure.title': 'العلاج بالضغط الصيني',
    'home.feature.acupressure.desc': '20 نقطة علاجية من الطب الصيني التقليدي',
    'home.feature.cranio.title': 'العلاج القحفي',
    'home.feature.cranio.desc': 'تقنيات الجمجمة للذاكرة والتركيز والقلق',
    'home.feature.breathing.title': 'تنفس 4-7-8',
    'home.feature.breathing.desc': 'تقنية علمية مع مؤقت وعلاج بالألوان متكامل',
    'home.feature.chromotherapy.title': 'العلاج بالألوان',
    'home.feature.chromotherapy.desc': 'ألوان علاجية مبنية على علم الأعصاب',
    'home.feature.sounds.title': 'أصوات متناغمة',
    'home.feature.sounds.desc': 'مكتبة كاملة + تكامل Spotify Premium',
    'home.feature.consultation.title': 'استشارات WhatsApp',
    'home.cta.title': 'مستعد للبدء؟',
    'home.cta.subtitle': 'انضم لآلاف الأشخاص الذين يحولون حياتهم',
    'home.cta.demo': 'جرب مجاناً',
    'home.cta.corporate': 'حلول الشركات',
    'home.compliance.title': 'الامتثال القانوني للشركات',
    'home.compliance.subtitle': 'امتثال كامل للتشريع البرازيلي'
  },

  bn: {
    // নেভিগেশন
    'nav.home': 'হোম',
    'nav.acupressure': 'আকুপ্রেশার',
    'nav.breathing': 'শ্বাস',
    'nav.premium': 'প্রিমিয়াম',
    'nav.corporate': 'কর্পোরেট',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.sounds': 'শব্দ',
    'nav.progress': 'অগ্রগতি',
    'nav.personalization': 'ব্যক্তিগতকরণ',
    'nav.login': 'লগইন',
    'nav.logout': 'লগআউট',

    // হোম
    'home.hero.title': 'সামগ্রিক থেরাপি দিয়ে আপনার জীবন পরিবর্তন করুন',
    'home.hero.subtitle': 'TCM আকুপ্রেশার, 4-7-8 শ্বাস, রঙ থেরাপি এবং সুরেলা শব্দ',
    'home.hero.startNow': 'এখনই শুরু করুন',
    'home.hero.createAccount': 'অ্যাকাউন্ট তৈরি করুন',
    'home.features.title': 'সম্পূর্ণ বৈশিষ্ট্য',
    'home.features.subtitle': 'আপনার সুস্থতার জন্য প্রয়োজনীয় সবকিছু',
    'home.feature.acupressure.title': 'TCM আকুপ্রেশার',
    'home.feature.acupressure.desc': 'ঐতিহ্যবাহী চীনা চিকিৎসার 20টি থেরাপিউটিক পয়েন্ট',
    'home.feature.cranio.title': 'ক্রেনিওপাংচার',
    'home.feature.cranio.desc': 'স্মৃতি, একাগ্রতা এবং উদ্বেগের জন্য মাথার কৌশল',
    'home.feature.breathing.title': '4-7-8 শ্বাস',
    'home.feature.breathing.desc': 'টাইমার এবং সমন্বিত রঙ থেরাপি সহ বৈজ্ঞানিক কৌশল',
    'home.feature.chromotherapy.title': 'রঙ থেরাপি',
    'home.feature.chromotherapy.desc': 'নিউরোসায়েন্স ভিত্তিক থেরাপিউটিক রঙ',
    'home.feature.sounds.title': 'সুরেলা শব্দ',
    'home.feature.sounds.desc': 'সম্পূর্ণ লাইব্রেরি + Spotify Premium ইন্টিগ্রেশন',
    'home.feature.consultation.title': 'WhatsApp পরামর্শ',
    'home.cta.title': 'শুরু করতে প্রস্তুত?',
    'home.cta.subtitle': 'হাজার হাজার মানুষের সাথে যোগ দিন যারা তাদের জীবন পরিবর্তন করছে',
    'home.cta.demo': 'বিনামূল্যে চেষ্টা করুন',
    'home.cta.corporate': 'কর্পোরেট সমাধান',
    'home.compliance.title': 'কর্পোরেট আইনি সম্মতি',
    'home.compliance.subtitle': 'ব্রাজিলীয় আইনের সাথে সম্পূর্ণ সম্মতি'
  },

  ru: {
    // Навигация
    'nav.home': 'Главная',
    'nav.acupressure': 'Акупрессура',
    'nav.breathing': 'Дыхание',
    'nav.premium': 'Премиум',
    'nav.corporate': 'Корпоративный',
    'nav.dashboard': 'Панель',
    'nav.sounds': 'Звуки',
    'nav.progress': 'Прогресс',
    'nav.personalization': 'Персонализация',
    'nav.login': 'Войти',
    'nav.logout': 'Выйти',

    // Главная
    'home.hero.title': 'Преобразите свою жизнь с помощью холистических терапий',
    'home.hero.subtitle': 'TCM акупрессура, дыхание 4-7-8, хромотерапия и гармонизирующие звуки',
    'home.hero.startNow': 'Начать сейчас',
    'home.hero.createAccount': 'Создать аккаунт',
    'home.features.title': 'Полные возможности',
    'home.features.subtitle': 'Все, что нужно для вашего благополучия',
    'home.feature.acupressure.title': 'TCM Акупрессура',
    'home.feature.acupressure.desc': '20 терапевтических точек традиционной китайской медицины',
    'home.feature.cranio.title': 'Краниопунктура',
    'home.feature.cranio.desc': 'Краниальные техники для памяти, концентрации и тревоги',
    'home.feature.breathing.title': 'Дыхание 4-7-8',
    'home.feature.breathing.desc': 'Научная техника с таймером и интегрированной хромотерапией',
    'home.feature.chromotherapy.title': 'Хромотерапия',
    'home.feature.chromotherapy.desc': 'Терапевтические цвета на основе нейронауки',
    'home.feature.sounds.title': 'Гармонизирующие звуки',
    'home.feature.sounds.desc': 'Полная библиотека + интеграция Spotify Premium',
    'home.feature.consultation.title': 'Консультации WhatsApp',
    'home.cta.title': 'Готовы начать?',
    'home.cta.subtitle': 'Присоединяйтесь к тысячам людей, меняющих свою жизнь',
    'home.cta.demo': 'Попробовать бесплатно',
    'home.cta.corporate': 'Корпоративные решения',
    'home.compliance.title': 'Корпоративное правовое соответствие',
    'home.compliance.subtitle': 'Полное соответствие бразильскому законодательству'
  },

  ja: {
    // ナビゲーション
    'nav.home': 'ホーム',
    'nav.acupressure': '指圧',
    'nav.breathing': '呼吸',
    'nav.premium': 'プレミアム',
    'nav.corporate': '企業向け',
    'nav.dashboard': 'ダッシュボード',
    'nav.sounds': 'サウンド',
    'nav.progress': '進捗',
    'nav.personalization': 'パーソナライゼーション',
    'nav.login': 'ログイン',
    'nav.logout': 'ログアウト',

    // ホーム
    'home.hero.title': 'ホリスティック療法で人生を変える',
    'home.hero.subtitle': 'TCM指圧、4-7-8呼吸法、色彩療法、調和音',
    'home.hero.startNow': '今すぐ始める',
    'home.hero.createAccount': 'アカウント作成',
    'home.features.title': '完全な機能',
    'home.features.subtitle': 'あなたの健康に必要なすべて',
    'home.feature.acupressure.title': 'TCM指圧',
    'home.feature.acupressure.desc': '伝統中国医学の20の治療ポイント',
    'home.feature.cranio.title': '頭鍼療法',
    'home.feature.cranio.desc': '記憶、集中力、不安のための頭部技術',
    'home.feature.breathing.title': '4-7-8呼吸法',
    'home.feature.breathing.desc': 'タイマーと統合色彩療法を備えた科学的技術',
    'home.feature.chromotherapy.title': '色彩療法',
    'home.feature.chromotherapy.desc': '神経科学に基づく治療色',
    'home.feature.sounds.title': '調和音',
    'home.feature.sounds.desc': '完全ライブラリ + Spotify Premium統合',
    'home.feature.consultation.title': 'WhatsApp相談',
    'home.cta.title': '始める準備はできましたか？',
    'home.cta.subtitle': '人生を変えている何千人もの人々に参加してください',
    'home.cta.demo': '無料で試す',
    'home.cta.corporate': '企業ソリューション',
    'home.compliance.title': '企業法的コンプライアンス',
    'home.compliance.subtitle': 'ブラジル法との完全な準拠'
  },

  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.acupressure': 'Akupressur',
    'nav.breathing': 'Atmung',
    'nav.premium': 'Premium',
    'nav.corporate': 'Unternehmen',
    'nav.dashboard': 'Dashboard',
    'nav.sounds': 'Klänge',
    'nav.progress': 'Fortschritt',
    'nav.personalization': 'Personalisierung',
    'nav.login': 'Anmelden',
    'nav.logout': 'Abmelden',

    // Startseite
    'home.hero.title': 'Verwandeln Sie Ihr Leben mit ganzheitlichen Therapien',
    'home.hero.subtitle': 'TCM Akupressur, 4-7-8 Atmung, Farbtherapie und harmonisierende Klänge',
    'home.hero.startNow': 'Jetzt beginnen',
    'home.hero.createAccount': 'Konto erstellen',
    'home.features.title': 'Vollständige Funktionen',
    'home.features.subtitle': 'Alles was Sie für Ihr Wohlbefinden brauchen',
    'home.feature.acupressure.title': 'TCM Akupressur',
    'home.feature.acupressure.desc': '20 therapeutische Punkte der Traditionellen Chinesischen Medizin',
    'home.feature.cranio.title': 'Kraniopunktur',
    'home.feature.cranio.desc': 'Schädeltechniken für Gedächtnis, Konzentration und Angst',
    'home.feature.breathing.title': '4-7-8 Atmung',
    'home.feature.breathing.desc': 'Wissenschaftliche Technik mit Timer und integrierter Farbtherapie',
    'home.feature.chromotherapy.title': 'Farbtherapie',
    'home.feature.chromotherapy.desc': 'Therapeutische Farben basierend auf Neurowissenschaft',
    'home.feature.sounds.title': 'Harmonisierende Klänge',
    'home.feature.sounds.desc': 'Vollständige Bibliothek + Spotify Premium Integration',
    'home.feature.consultation.title': 'WhatsApp Beratungen',
    'home.cta.title': 'Bereit anzufangen?',
    'home.cta.subtitle': 'Schließen Sie sich Tausenden von Menschen an, die ihr Leben verändern',
    'home.cta.demo': 'Kostenlos testen',
    'home.cta.corporate': 'Unternehmenslösungen',
    'home.compliance.title': 'Unternehmens-Rechtskonformität',
    'home.compliance.subtitle': 'Vollständige Einhaltung der brasilianischen Gesetzgebung'
  },

  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.acupressure': 'Acupression',
    'nav.breathing': 'Respiration',
    'nav.premium': 'Premium',
    'nav.corporate': 'Entreprise',
    'nav.dashboard': 'Tableau de bord',
    'nav.sounds': 'Sons',
    'nav.progress': 'Progrès',
    'nav.personalization': 'Personnalisation',
    'nav.login': 'Connexion',
    'nav.logout': 'Déconnexion',

    // Accueil
    'home.hero.title': 'Transformez votre vie avec des thérapies holistiques',
    'home.hero.subtitle': 'Acupression MTC, respiration 4-7-8, chromothérapie et sons harmonisants',
    'home.hero.startNow': 'Commencer maintenant',
    'home.hero.createAccount': 'Créer un compte',
    'home.features.title': 'Fonctionnalités complètes',
    'home.features.subtitle': 'Tout ce dont vous avez besoin pour votre bien-être',
    'home.feature.acupressure.title': 'Acupression MTC',
    'home.feature.acupressure.desc': '20 points thérapeutiques de Médecine Traditionnelle Chinoise',
    'home.feature.cranio.title': 'Craniopuncture',
    'home.feature.cranio.desc': 'Techniques crâniennes pour mémoire, concentration et anxiété',
    'home.feature.breathing.title': 'Respiration 4-7-8',
    'home.feature.breathing.desc': 'Technique scientifique avec minuteur et chromothérapie intégrée',
    'home.feature.chromotherapy.title': 'Chromothérapie',
    'home.feature.chromotherapy.desc': 'Couleurs thérapeutiques basées sur les neurosciences',
    'home.feature.sounds.title': 'Sons harmonisants',
    'home.feature.sounds.desc': 'Bibliothèque complète + intégration Spotify Premium',
    'home.feature.consultation.title': 'Consultations WhatsApp',
    'home.cta.title': 'Prêt à commencer?',
    'home.cta.subtitle': 'Rejoignez des milliers de personnes transformant leur vie',
    'home.cta.demo': 'Essayer gratuitement',
    'home.cta.corporate': 'Solutions d\'entreprise',
    'home.compliance.title': 'Conformité légale d\'entreprise',
    'home.compliance.subtitle': 'Conformité complète avec la législation brésilienne'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]); // Português como padrão

  useEffect(() => {
    // Carregar idioma salvo ou detectar idioma do navegador
    const savedLanguage = localStorage.getItem('xzenpress_language');
    if (savedLanguage) {
      const found = languages.find(lang => lang.code === savedLanguage);
      if (found) {
        setCurrentLanguage(found);
        return;
      }
    }

    // Detectar idioma do navegador
    const browserLang = navigator.language.split('-')[0];
    const detected = languages.find(lang => lang.code === browserLang);
    if (detected) {
      setCurrentLanguage(detected);
    }
  }, []);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('xzenpress_language', language.code);
    
    // Atualizar direção do texto para idiomas RTL
    document.documentElement.dir = language.direction;
    document.documentElement.lang = language.code;
  };

  const t = (key: string): string => {
    const translation = translations[currentLanguage.code]?.[key];
    if (translation) {
      return translation;
    }
    
    // Fallback para português se a tradução não existir
    const fallback = translations.pt[key];
    if (fallback) {
      return fallback;
    }
    
    // Se nem o fallback existir, retornar a chave
    console.warn(`Translation missing for key: ${key} in language: ${currentLanguage.code}`);
    return key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};